-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = "JUROR",public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS "PHONE_LOG_UPDATE" ON "PHONE_LOG" CASCADE;
CREATE OR REPLACE FUNCTION "trigger_fct_phone_log_update"() RETURNS trigger AS $BODY$
BEGIN
            :new.last_update := SYSDATE;
       END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION "trigger_fct_phone_log_update"() FROM PUBLIC;

CREATE TRIGGER "PHONE_LOG_UPDATE"
	BEFORE INSERT OR UPDATE ON "PHONE_LOG" "JUROR".phone_log_update
       BEFORE INSERT OR UPDATE
       ON phone_log
       REFERENCING NEW AS new
       FOR EACH ROW
 FOR EACH ROW
	EXECUTE PROCEDURE "trigger_fct_phone_log_update"();

