-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = "JUROR",public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS "POOL_UPDATE" ON "POOL" CASCADE;
CREATE OR REPLACE FUNCTION "trigger_fct_pool_update"() RETURNS trigger AS $BODY$
BEGIN
   If (:new.read_only <> '*' and :old.read_only <> '*') or :new.read_only is null 
      or :new.read_only = 'N' Then
            :new.last_update := SYSDATE;
   End If;
   IF :old.status is null THEN
      IF :new.status = 6 and :new.disq_code = 'A' and :new.responded = 'N' THEN
         :new.summons_file := 'Disq. on selection';
      END IF;
   END IF;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION "trigger_fct_pool_update"() FROM PUBLIC;

CREATE TRIGGER "POOL_UPDATE"
	BEFORE INSERT OR UPDATE ON "POOL" "JUROR".pool_update
       BEFORE
       INSERT OR UPDATE ON pool
       REFERENCING NEW AS new OLD AS old
       FOR EACH ROW
 FOR EACH ROW
	EXECUTE PROCEDURE "trigger_fct_pool_update"();

