-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = JUROR,public;




CREATE OR REPLACE PROCEDURE auto_generate_get_print_file_name () AS $body$
BEGIN
  --  lc_Job_Type	  := current_setting('');
  --  lc_EnglishFormType := current_setting('');
  --  lc_WelshFormType	  := current_setting('');
  --  lc_OtherInformation:= current_setting('');
  --  lc_HistoryCode	  := current_setting('');

  SELECT sum(number_of_items)
  FROM 	 abaccus
  WHERE	 form_type = current_setting('auto_generate_lc_englishformtype', false)::form_attr.form_type%type
  AND	 date_trunc('day', creation_date) = date_trunc('day', current_setting('auto_generate_ld_begin_time', false)::timestamp(0));

  SELECT sum(number_of_items)
  FROM 	 abaccus
  WHERE	 form_type = current_setting('auto_generate_lc_welshformtype', false)::form_attr.form_type%type
  AND	 date_trunc('day', creation_date) = date_trunc('day', current_setting('auto_generate_ld_begin_time', false)::timestamp(0));


-- Get nextval from sequence data_file_no only if records exist for English letters
   IF current_setting('auto_generate_ln_english_processed_count', false)::integer > 0 THEN
   	  PERFORM 'JURY'||RPAD(nextval('data_file_no'),4,'0')||current_setting('auto_generate_lc_fileextension', false)::varchar(30);
   END IF;


-- Get nextval from sequence data_file_no only if records exist for Welsh letters
  IF current_setting('auto_generate_ln_welsh_processed_count', false)::integer > 0 THEN
	  PERFORM 'JURY'||RPAD(nextval('data_file_no'),4,'0')||current_setting('auto_generate_lc_fileextension', false)::varchar(30);
  END IF;



 END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE auto_generate_get_print_file_name () FROM PUBLIC;
