-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = JUROR,public;


/****************************************************************************************************************************/

CREATE OR REPLACE PROCEDURE auto_generate_populate_print_files () AS $body$
BEGIN

   -- Get print file names
      CALL auto_generate_get_print_file_name();

  -- Now populate print_files table
 	INSERT into print_files(printfile_name, creation_date, form_type, detail_rec)
	SELECT CASE WHEN lang='E' THEN  current_setting('auto_generate_lc_englishfile')::print_files.printfile_name%type  ELSE current_setting('auto_generate_lc_welshfile')::print_files.printfile_name%type END ,
		   current_setting('auto_generate_ld_begin_time')::timestamp(0),
		   CASE WHEN lang='E' THEN  current_setting('auto_generate_lc_englishformtype')::form_attr.form_type%type  ELSE current_setting('auto_generate_lc_welshformtype')::form_attr.form_type%type END ,
		   details
	FROM   temp_auto_generate_lett;


 END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE auto_generate_populate_print_files () FROM PUBLIC;
