-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = JUROR,public;


/****************************************************************************************************************************/

CREATE OR REPLACE PROCEDURE auto_generate_populate_part_hist () AS $body$
BEGIN

 	INSERT INTO  part_hist(owner, part_no,date_part,history_code,user_id,other_information,pool_no)
  	SELECT '400', part_no,clock_timestamp(),current_setting('auto_generate_lc_historycode')::part_hist.history_code%type,'SYSTEM',current_setting('auto_generate_lc_otherinformation')::part_hist.other_information%type,pool_no
  	FROM	 temp_auto_generate_lett;


 END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE auto_generate_populate_part_hist () FROM PUBLIC;
