-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.4;sid=xe;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE OR REPLACE PACKAGE get_pool_transfer_return_date  IS

function get_return_date return date;

END get_pool_transfer_return_date;


CREATE OR REPLACE PACKAGE BODY get_pool_transfer_return_date AS
/*************************************************************************
 *  History
 *
 *	Version Name		  Date		 Desc
 *	======= ========= ======== ====
 *  V1.0    ???       ???      Initial version
 *	V1.3    Kal Sohal 17/01/07 SCR 4362 - Pools transferring too early.
 *                             Modify code which determines if procedure is being run before 6pm on a Friday by
 *                             reference to the dates day number 6 with NEW reference to actual dates day name 'fri'.
 ************************************************************************/

FUNCTION get_return_date
return date IS
	ln_Day	 varchar2(3);
	ln_DeadLine NUMBER :=10;
	ld_EffectiveDate date;
	pd_LatestReturnDate date;
begin
	      ld_EffectiveDate := sysdate;
    	  	IF ((TO_NUMBER(TO_CHAR(ld_EffectiveDate,'sssss')) <= 64800)
          -- KSO v1.3 >>
	        -- AND (TO_NUMBER(TO_CHAR(ld_EffectiveDate,'d'))) = 6)   THEN -- Set the effective date to previous day
             AND (TO_CHAR(ld_EffectiveDate,'dy') = 'fri'))  THEN -- Set the effective date to previous day
          -- KSO v1.3 <<
 		  ld_EffectiveDate := TRUNC(ld_EffectiveDate)-1; 	      -- if the procedure runs before 6 pm on a Friday
 		END IF;
	    ln_Day := TO_CHAR(ld_EffectiveDate,'dy');
        CASE ln_Day
          WHEN 'mon' THEN ld_EffectiveDate := TRUNC(ld_EffectiveDate - 3); -- Monday
          WHEN 'tue' THEN ld_EffectiveDate := TRUNC(ld_EffectiveDate - 4); -- Tuesday
	      WHEN 'wed' THEN ld_EffectiveDate := TRUNC(ld_EffectiveDate - 5); -- Wednesday
          WHEN 'thu' THEN ld_EffectiveDate := TRUNC(ld_EffectiveDate - 6); --Thursday
	      WHEN 'fri' THEN ld_EffectiveDate := TRUNC(ld_EffectiveDate); -- Friday
          WHEN 'sat' THEN ld_EffectiveDate := TRUNC(ld_EffectiveDate - 1 ); -- Saturday
	      WHEN 'sun' THEN ld_EffectiveDate := TRUNC(ld_EffectiveDate - 2); --Sunday
		END CASE;
 	   pd_LatestReturnDate   := ld_EffectiveDate + ln_DeadLine + 5;
return pd_LatestReturnDate;
END get_return_date;
END get_pool_transfer_return_date;