-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.2;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = hk,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW coroner_pool AS SELECT * FROM juror.coroner_pool;
CREATE OR REPLACE VIEW coroner_pool_detail AS SELECT * FROM juror.coroner_pool_detail;
CREATE OR REPLACE VIEW error_log AS SELECT * FROM juror.error_log;
CREATE OR REPLACE VIEW hk_run_log AS SELECT * FROM juror.hk_run_log;
CREATE OR REPLACE VIEW holidays AS SELECT * FROM juror.holidays;
CREATE OR REPLACE VIEW pl_xml_status AS SELECT * FROM juror.pl_xml_status;
