-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.2;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = hk,public;


   -----------
   --
   -----------
      


CREATE OR REPLACE PROCEDURE hk.housekeeping_fetch_parameters () AS $body$
DECLARE


     -- Get parameters from main param table. There must be three values - if any are not present then
     -- raise e_param_error execpetion which is handled in main block
   
     c_hk_params CURSOR FOR
       SELECT key
       ,      value
       FROM   hk_params;

   
BEGIN
   
  
     FOR l_hk_params IN c_hk_params LOOP
     
       IF l_hk_params.key = 1 THEN
         PERFORM set_config('housekeeping.l_param_court_threshold', l_hk_params.value, false);
       ELSIF l_hk_params.key = 2 THEN
         PERFORM set_config('housekeeping.l_param_bureau_threshold', l_hk_params.value, false);
       ELSIF l_hk_params.key = 3 THEN
         PERFORM set_config('housekeeping.l_param_max_deletes', l_hk_params.value, false);
       END IF;
     END LOOP;

     housekeeping_write_params_to_log;

     -- raise error if database stored parameters are not all present
     IF current_setting('housekeeping.l_param_court_threshold') = '' OR current_setting('housekeeping.l_param_bureau_threshold') = '' OR current_setting('housekeeping.l_param_max_deletes') = '' THEN
       RAISE EXCEPTION 'e_param_error' USING ERRCODE = '50002';
     END IF;

     -- raise error if command line parameters are not all present
     IF p_owner_restrict IS NULL OR
        p_read_only_mode IS NULL OR       
        p_max_time       IS NULL OR
        p_owner_restrict NOT IN ('YES','NO') OR
        NOT p_max_time > 0 THEN
        
        RAISE EXCEPTION 'e_param_error' USING ERRCODE = '50002';

     END IF;
 
     
   EXCEPTION
     WHEN others THEN
       RAISE EXCEPTION 'e_param_error' USING ERRCODE = '50002';

   END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE hk.housekeeping_fetch_parameters () FROM PUBLIC;
