-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.2;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = hk,public;



   -----------
   --
   -----------
   


CREATE OR REPLACE PROCEDURE hk.housekeeping_parent_delete_trial () AS $body$
DECLARE

   
     l_start timestamp(0);
     l_start_Accused timestamp(0);
     l_deleted bigint;
     l_deleted_accused bigint;
     l_end   timestamp(0);

   
BEGIN
   
     PERFORM set_config('housekeeping.l_error_stage', 'ACCUSED', false);
     l_start_accused := clock_timestamp();

     SELECT COUNT(*) INTO STRICT current_setting('housekeeping.l_accused')::logs('PRE') FROM accused;

     utl_file.put_line(l_file,' ',TRUE);
     utl_file.put_line(l_file,'Row Counts for POOL PARENT tables',TRUE);
     utl_file.put_line(l_file,'Table,Selected,Start Time,End Time,Before,After,Deleted',TRUE);
  
     
     DELETE FROM accused ac
     WHERE  EXISTS (SELECT null 
                    FROM   trial tr
                    WHERE  trial_end_date + current_setting('housekeeping.l_param_court_threshold')::integer < clock_timestamp()
                    AND    tr.owner = ac.owner
                    AND    tr.trial_no = ac.trial_no
                    AND NOT EXISTS (SELECT null
                                    FROM   panel pl
                                    WHERE  tr.trial_no = pl.trial_no 
                                    AND    tr.owner = pl.owner
                                    )
                    );

     GET DIAGNOSTICS l_deleted_accused = ROW_COUNT;
     l_end      := clock_timestamp();

     PERFORM set_config('housekeeping.l_error_stage', 'TRIAL', false);
     l_start := clock_timestamp();

     SELECT COUNT(*) INTO STRICT current_setting('housekeeping.l_trial')::logs('PRE') FROM trial;

     DELETE FROM trial ab
     WHERE  trial_end_date + current_setting('housekeeping.l_param_court_threshold')::integer < clock_timestamp()
     AND NOT EXISTS (SELECT null
                     FROM   panel pl
                     WHERE  ab.trial_no = pl.trial_no 
                     AND    ab.owner = pl.owner
                     );

    GET DIAGNOSTICS l_deleted = ROW_COUNT;

     IF p_read_only_mode THEN
       ROLLBACK;
     ELSE
       COMMIT;
     END IF;

     SELECT COUNT(*) INTO STRICT current_setting('housekeeping.l_accused')::logs('POST') FROM accused;
     SELECT COUNT(*) INTO STRICT current_setting('housekeeping.l_trial')::logs('POST') FROM trial;

     utl_file.put_line(l_file,'TRIAL,'||l_deleted||','||TO_CHAR(l_start,'DD-MM-YYYY hh24:MI:SS')||','||TO_CHAR(clock_timestamp(),'DD-MM-YYYY hh24:MI:SS')||','||current_setting('housekeeping.l_trial')::logs('PRE')||','||current_setting('housekeeping.l_trial')::logs('POST')||','||current_setting('housekeeping.l_trial')::logs('PRE')-current_setting('housekeeping.l_trial')::logs('POST')::varchar,TRUE);
     utl_file.put_line(l_file,'ACCUSED,'||l_deleted_accused||','||TO_CHAR(l_start_accused,'DD-MM-YYYY hh24:MI:SS')||','||TO_CHAR(l_end,'DD-MM-YYYY hh24:MI:SS')||','||current_setting('housekeeping.l_accused')::logs('PRE')||','||current_setting('housekeeping.l_accused')::logs('POST')||','||current_setting('housekeeping.l_accused')::logs('PRE')-current_setting('housekeeping.l_accused')::logs('POST')::varchar ,TRUE);

 
   EXCEPTION 
     WHEN others THEN
     
       ROLLBACK;

       PERFORM set_config('housekeeping.l_err_msg', SUBSTR(sqlerrm,1,200), false);

       RAISE EXCEPTION 'e_delete_error' USING ERRCODE = '50001';
 
   END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE hk.housekeeping_parent_delete_trial () FROM PUBLIC;
