-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.2;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = hk,public;


   -----------
   --
   -----------
CREATE OR REPLACE PROCEDURE hk.housekeeping_delete_sa_pl_xml_status () AS $body$
DECLARE


    l_start timestamp(0);
    l_deleted bigint;

   
BEGIN
    
     l_start := clock_timestamp();

     SELECT COUNT(*) INTO STRICT current_setting('housekeeping.l_pl_xml_status')::logs('PRE') FROM pl_xml_status;

     DELETE FROM pl_xml_status
     WHERE  date_time_stamp + current_setting('housekeeping.l_param_court_threshold')::integer < clock_timestamp();

     GET DIAGNOSTICS l_deleted = ROW_COUNT;

     IF p_read_only_mode THEN
       ROLLBACK;
     ELSE
       COMMIT;
     END IF;

     SELECT COUNT(*) INTO STRICT current_setting('housekeeping.l_pl_xml_status')::logs('POST') FROM pl_xml_status;

     utl_file.put_line(l_file,'PL_XML_STATUS,'||l_deleted||','||TO_CHAR(l_start,'DD-MM-YYYY hh24:MI:SS')||','||TO_CHAR(clock_timestamp(),'DD-MM-YYYY hh24:MI:SS')||','||current_setting('housekeeping.l_pl_xml_status')::logs('PRE')||','||current_setting('housekeeping.l_pl_xml_status')::logs('POST')||','||current_setting('housekeeping.l_pl_xml_status')::logs('PRE')-current_setting('housekeeping.l_pl_xml_status')::logs('POST')::varchar,TRUE);


     housekeeping_check_time_expired;

   EXCEPTION 
     WHEN SQLSTATE '50004' THEN
       RAISE EXCEPTION 'e_timeout' USING ERRCODE = '50004';

     WHEN others THEN

       ROLLBACK;

       PERFORM set_config('housekeeping.l_err_msg', SUBSTR(sqlerrm,1,200), false);
       utl_file.put_line(l_file,'ERROR Delete from PL_XML_STATUS',TRUE);
       utl_file.put_line(l_file,current_setting('housekeeping.l_err_msg')::varchar(200),TRUE);

   END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE hk.housekeeping_delete_sa_pl_xml_status () FROM PUBLIC;
