-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.2;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = hk,public;

   
   
   -----------
   --
   -----------
  
  


CREATE OR REPLACE PROCEDURE hk.housekeeping_write_child_rowcounts () AS $body$
DECLARE


      -- writes results log and closes file
  
      
BEGIN
  
      utl_file.put_line(l_file,' ',TRUE);
      utl_file.put_line(l_file,'Row Counts for POOL child tables',TRUE);
      utl_file.put_line(l_file,'Table,Before,After,Deleted',TRUE);
      utl_file.put_line(l_file,'AUDIT_F_REPORT,'||l_audit_f_report('PRE')||','||l_audit_f_report('POST')||','||(l_audit_f_report('PRE')-l_audit_f_report('POST')),TRUE);
      utl_file.put_line(l_file,'APPEARANCES,'||l_appearances('PRE')||','||l_appearances('POST')||','||(l_appearances('PRE')-l_appearances('POST')),TRUE);
      utl_file.put_line(l_file,'AUDIT_REPORT,'||l_audit_report('PRE')||','||l_audit_report('POST')||','||(l_audit_report('PRE')-l_audit_report('POST')),TRUE);
      utl_file.put_line(l_file,'CERT_LETT,'||l_cert_lett('PRE')||','||l_cert_lett('POST')||','||(l_cert_lett('PRE')-l_cert_lett('POST')),TRUE);
      utl_file.put_line(l_file,'CONFIRM_LETT,'||l_confirm_lett('PRE')||','||l_confirm_lett('POST')||','||(l_confirm_lett('PRE')-l_confirm_lett('POST')),TRUE);
      utl_file.put_line(l_file,'DISQ_LETT,'||l_disq_lett('PRE')||','||l_disq_lett('POST')||','||(l_disq_lett('PRE')-l_disq_lett('POST')),TRUE);
      utl_file.put_line(l_file,'DEFER_DBF,'||l_defer_dbf('PRE')||','||l_defer_dbf('POST')||','||(l_defer_dbf('PRE')-l_defer_dbf('POST')),TRUE);
      utl_file.put_line(l_file,'DEF_LETT,'||current_setting('housekeeping.l_def_lett')::logs('PRE')||','||current_setting('housekeeping.l_def_lett')::logs('POST')||','||(current_setting('housekeeping.l_def_lett')::logs('PRE')-current_setting('housekeeping.l_def_lett')::logs('POST')),TRUE);
      utl_file.put_line(l_file,'DEF_DENIED,'||current_setting('housekeeping.l_def_denied')::logs('PRE')||','||current_setting('housekeeping.l_def_denied')::logs('POST')||','||(current_setting('housekeeping.l_def_denied')::logs('PRE')-current_setting('housekeeping.l_def_denied')::logs('POST')),TRUE);
      utl_file.put_line(l_file,'EXC_LETT,'||current_setting('housekeeping.l_exc_lett')::logs('PRE')||','||current_setting('housekeeping.l_exc_lett')::logs('POST')||','||(current_setting('housekeeping.l_exc_lett')::logs('PRE')-current_setting('housekeeping.l_exc_lett')::logs('POST')),TRUE);
      utl_file.put_line(l_file,'EXC_DENIED_LETT,'||current_setting('housekeeping.l_exc_denied_lett')::logs('PRE')||','||current_setting('housekeeping.l_exc_denied_lett')::logs('POST')||','||(current_setting('housekeeping.l_exc_denied_lett')::logs('PRE')-current_setting('housekeeping.l_exc_denied_lett')::logs('POST')),TRUE);
      utl_file.put_line(l_file,'FTA_LETT,'||current_setting('housekeeping.l_fta_lett')::logs('PRE')||','||current_setting('housekeeping.l_fta_lett')::logs('POST')||','||(current_setting('housekeeping.l_fta_lett')::logs('PRE')-current_setting('housekeeping.l_fta_lett')::logs('POST')),TRUE);
      utl_file.put_line(l_file,'MANUALS,'||l_manuals('PRE')||','||l_manuals('POST')||','||(l_manuals('PRE')-l_manuals('POST')),TRUE);
      utl_file.put_line(l_file,'PANEL,'||current_setting('housekeeping.l_panel')::logs('PRE')||','||current_setting('housekeeping.l_panel')::logs('POST')||','||(current_setting('housekeeping.l_panel')::logs('PRE')-current_setting('housekeeping.l_panel')::logs('POST')),TRUE);
      utl_file.put_line(l_file,'PART_AMENDMENTS,'||l_part_amendments('PRE')||','||l_part_amendments('POST')||','||(l_part_amendments('PRE')-l_part_amendments('POST')),TRUE);
      utl_file.put_line(l_file,'PART_HIST,'||l_part_hist('PRE')||','||l_part_hist('POST')||','||(l_part_hist('PRE')-l_part_hist('POST')),TRUE);
      utl_file.put_line(l_file,'PART_EXPENSES,'||l_part_expenses('PRE')||','||l_part_expenses('POST')||','||(l_part_expenses('PRE')-l_part_expenses('POST')),TRUE);
      utl_file.put_line(l_file,'POSTPONE_LETT,'||current_setting('housekeeping.l_postpone_lett')::logs('PRE')||','||current_setting('housekeeping.l_postpone_lett')::logs('POST')||','||(current_setting('housekeeping.l_postpone_lett')::logs('PRE')-current_setting('housekeeping.l_postpone_lett')::logs('POST')),TRUE);
      utl_file.put_line(l_file,'PHONE_LOG,'||current_setting('housekeeping.l_phone_log')::logs('PRE')||','||current_setting('housekeeping.l_phone_log')::logs('POST')||','||(current_setting('housekeeping.l_phone_log')::logs('PRE')-current_setting('housekeeping.l_phone_log')::logs('POST')),TRUE);
      utl_file.put_line(l_file,'REQUEST_LETT,'||current_setting('housekeeping.l_request_lett')::logs('PRE')||','||current_setting('housekeeping.l_request_lett')::logs('POST')||','||(current_setting('housekeeping.l_request_lett')::logs('PRE')-current_setting('housekeeping.l_request_lett')::logs('POST')),TRUE);
      utl_file.put_line(l_file,'UNDELIVR,'||current_setting('housekeeping.l_undeliver')::logs('PRE')||','||current_setting('housekeeping.l_undeliver')::logs('POST')||','||(current_setting('housekeeping.l_undeliver')::logs('PRE')-current_setting('housekeeping.l_undeliver')::logs('POST')),TRUE);
      utl_file.put_line(l_file,' ',TRUE);
      utl_file.put_line(l_file,'Row Counts for POOL table',TRUE);
      utl_file.put_line(l_file,'Table,Before,After,Deleted',TRUE);
      utl_file.put_line(l_file,'POOL,'||current_setting('housekeeping.l_pool')::logs('PRE')||','||current_setting('housekeeping.l_pool')::logs('POST')||','||(current_setting('housekeeping.l_pool')::logs('PRE')-current_setting('housekeeping.l_pool')::logs('POST')),TRUE);



    EXCEPTION 
      WHEN OTHERS THEN
      
        RAISE e_log_error;

    END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE hk.housekeeping_write_child_rowcounts () FROM PUBLIC;
