-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = "JUROR_DIGITAL",public;
\set ON_ERROR_STOP ON

-- Oracle tablespaces export, please edit path to match your filesystem.
-- In PostgreSQl the path must be a directory and is expected to already exists
ALTER INDEX app_settings_pk SET TABLESPACE juror_digital_data;
ALTER INDEX change_log_item_pk SET TABLESPACE juror_digital_data;
ALTER INDEX change_log_pk SET TABLESPACE juror_digital_data;
ALTER INDEX cjs_employment_pk SET TABLESPACE juror_digital_data;
ALTER INDEX contact_log_ext_pk SET TABLESPACE juror_digital_data;
ALTER INDEX coroner_pool_ext_pk SET TABLESPACE juror_digital_data;
ALTER INDEX court_region_name_unq SET TABLESPACE juror_digital_data;
ALTER INDEX court_region_pk SET TABLESPACE juror_digital_data;
ALTER INDEX court_whitelist_code_unique SET TABLESPACE juror_digital_data;
ALTER INDEX expenses_rates_id_pk SET TABLESPACE juror_digital_data;
ALTER INDEX jr_ps_lsl_jn SET TABLESPACE juror_digital_data;
ALTER INDEX juror_response_pk SET TABLESPACE juror_digital_data;
ALTER INDEX messages_pk SET TABLESPACE juror_digital_data;
ALTER INDEX ntf_id_pk SET TABLESPACE juror_digital_data;
ALTER INDEX ntm_template_id_pk SET TABLESPACE juror_digital_data;
ALTER INDEX ntm_template_name_unq SET TABLESPACE juror_digital_data;
ALTER INDEX paper_cjs_employment_pk SET TABLESPACE juror_digital_data;
ALTER INDEX paper_response_pk SET TABLESPACE juror_digital_data;
ALTER INDEX paper_special_needs_pk SET TABLESPACE juror_digital_data;
ALTER INDEX pool_extend_pk SET TABLESPACE juror_digital_data;
ALTER INDEX pool_member_ext_pk SET TABLESPACE juror_digital_data;
ALTER INDEX pool_total_required_pk SET TABLESPACE juror_digital_data;
ALTER INDEX region_notify_template_pk SET TABLESPACE juror_digital_data;
ALTER INDEX spec_need_pk SET TABLESPACE juror_digital_data;
ALTER INDEX staff_audit_pk SET TABLESPACE juror_digital_data;
ALTER INDEX staff_juror_response_audit_pk SET TABLESPACE juror_digital_data;
ALTER INDEX staff_pk SET TABLESPACE juror_digital_data;
ALTER INDEX stats_auto_processed_id_pk SET TABLESPACE juror_digital_data;
ALTER INDEX stats_deferrals_pk SET TABLESPACE juror_digital_data;
ALTER INDEX stats_excusals_pk SET TABLESPACE juror_digital_data;
ALTER INDEX stats_nonresp_id_pk SET TABLESPACE juror_digital_data;
ALTER INDEX stats_resp_time_id_pk SET TABLESPACE juror_digital_data;
ALTER INDEX stats_third_online_id_pk SET TABLESPACE juror_digital_data;
ALTER INDEX stats_unprocessed_resp_id_pk SET TABLESPACE juror_digital_data;
ALTER INDEX stats_welsh_online_resp_id_pk SET TABLESPACE juror_digital_data;
ALTER INDEX survey_response_id_pk SET TABLESPACE juror_digital_data;
ALTER INDEX sys_c008428 SET TABLESPACE juror_digital_data;
ALTER INDEX sys_c008429 SET TABLESPACE juror_digital_data;
ALTER INDEX voters_pk SET TABLESPACE juror_digital_data;
ALTER INDEX schema_version_pk SET TABLESPACE juror_digital_data;
ALTER INDEX schema_version_s_idx SET TABLESPACE juror_digital_data;
