-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = JUROR,public;




CREATE OR REPLACE PROCEDURE reset_clear_juror_data () AS $body$
BEGIN

     EXECUTE 'Truncate table attendance';
     EXECUTE 'Truncate table part_expenses';
     EXECUTE 'Truncate table appearances';
     EXECUTE 'Truncate table acct_pay_data';
     EXECUTE 'Truncate table audit_report';
     EXECUTE 'Truncate table audit_f_report';

     EXECUTE 'Truncate table def_lett';
     EXECUTE 'Truncate table exc_lett';
     EXECUTE 'Truncate table fta_lett';
     EXECUTE 'Truncate table disq_lett';
     EXECUTE 'Truncate table exc_denied_lett';
     EXECUTE 'Truncate table request_lett';
     EXECUTE 'Truncate table def_denied';
     EXECUTE 'Truncate table aramis_payments';
     EXECUTE 'Truncate table cert_lett';
     EXECUTE 'Truncate table confirm_lett';
     EXECUTE 'Truncate table postpone_lett';
     EXECUTE 'Truncate table release_lett';

     EXECUTE 'Truncate table panel';
     EXECUTE 'Truncate table trial';

     EXECUTE 'Truncate table phoenix_temp';
     EXECUTE 'Truncate table juror';
     EXECUTE 'Truncate table juror_court_police_check';

     EXECUTE 'Truncate table current_trans';
     EXECUTE 'Truncate table peak_usage';
     EXECUTE 'Truncate table pool_stats';
     EXECUTE 'Truncate table manuals';
     EXECUTE 'Truncate table part_amendments';
     EXECUTE 'Truncate table part_hist';
     EXECUTE 'Truncate table phone_log';
     EXECUTE 'Truncate table defer_dbf';
     EXECUTE 'Truncate table pool_comments';
     EXECUTE 'Truncate table pool_hist';
     EXECUTE 'Truncate table pool';
     EXECUTE 'Truncate table unique_pool';

     EXECUTE 'Truncate table coroner_pool_detail';
     EXECUTE 'Truncate table coroner_pool';

     EXECUTE 'Truncate table holidays';

     EXECUTE 'Truncate table abaccus';
     EXECUTE 'Truncate table print_files';
     EXECUTE 'Truncate table content_store';

  END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE reset_clear_juror_data () FROM PUBLIC;
