-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = JUROR,public;




CREATE OR REPLACE PROCEDURE reset_refresh_voters (p_loc_code text ) AS $body$
DECLARE


  -- Param in: p_loc_code - Either '000' for all locations otherwise valid court location.
  --
  -- Performs refresh of the votersnnn tables
  -- If parameter in is '000' then refresh is performed for ALL court locations
  -- otherwise it is just for the specified court location.
  l_zip varchar(12);
  l_sql varchar(600);

  c_voters_table CURSOR FOR
       SELECT tname, Substr(tname, 7, 3) loc_code
       from tab
  	 where tname like CASE WHEN p_loc_code='000' THEN 'VOTERS%'  ELSE 'VOTERS'||p_loc_code END;

BEGIN

   	 FOR ii in c_voters_table LOOP
       -- clear down the voters table
       l_sql := 'Truncate table VOTERS'||ii.loc_code;
       EXECUTE l_sql;

  	 	 -- get post code from court_location
       select cl.loc_zip
        into STRICT l_zip
        from court_location cl
        where cl.loc_code = ii.loc_code;

        -- Ensure psotcode is in the catchment area list
        -- Assumes loc_zip contains a space
        insert into court_catchment_area(SELECT substr(loc_zip,1,position(' ' in loc_zip)-1),loc_code from court_location
        where loc_code = ii.loc_code
        EXCEPT
        SELECT postcode, loc_code from court_catchment_area);

       -- Insert 999 rows into votersnnn
       -- Sample data
       -- PART_NO	TITLE	LNAME	FNAME	DOB	FLAGS	ADDRESS	ADDRESS2	ADDRESS3	ADDRESS4	ADDRESS5	ADDRESS6	ZIP
       -- 712700001		LNAMEONE	FNAMEONE			1 STREET NAME		ANYTOWN				B4 7NA
        l_sql :=
        'Insert into VOTERS'||ii.loc_code||
        ' (PART_NO, REGISTER_LETT, POLL_NUMBER, NEW_MARKER, TITLE, LNAME, FNAME, DOB, FLAGS,'||
        ' ADDRESS, ADDRESS2, ADDRESS3, ADDRESS4, ADDRESS5, ADDRESS6, ZIP,'||
        ' DATE_SELECTED1, DATE_SELECTED2, DATE_SELECTED3, REC_NUM, PERM_DISQUAL, SOURCE_ID)'||
        '(select ''6''||'||ii.loc_code||'||LPad(rownum, 5,''0''),'||
        'rownum,'||
        'rownum,'||
        'null,'||
        'null,'||
        '''LNAME''||rownum,'||
        '''FNAME''||rownum,'||
        'null,'||
        'decode(Mod(rownum, 100),0,''X'',null),'||
        'rownum||'' STREET NAME'','||
        '''ANYTOWN'','||
        'null,'||
        'null,'||
        'null,'||
        'null,'||
        ''''||l_zip||''','||
        'null,'||
        'null,'||
        'null,'||
        'rownum,'||
        'null,'||
        'null'||
        ' from dual connect by level < 1000)';
        EXECUTE l_sql;

        l_sql := 'Update VOTERS'||ii.loc_code||' set fname = replace(fname,''1'',''ONE''),'||' lname = replace(lname,''1'',''ONE'')';
        EXECUTE l_sql;

        l_sql := 'Update VOTERS'||ii.loc_code||' set fname = replace(fname,''2'',''TWO''),'||' lname = replace(lname,''2'',''TWO'')';
        EXECUTE l_sql;

        l_sql := 'Update VOTERS'||ii.loc_code||' set fname = replace(fname,''3'',''THREE''),'||' lname = replace(lname,''3'',''THREE'')';
        EXECUTE l_sql;

        l_sql := 'Update VOTERS'||ii.loc_code||' set fname = replace(fname,''4'',''FOUR''),'||' lname = replace(lname,''4'',''FOUR'')';
        EXECUTE l_sql;

        l_sql := 'Update VOTERS'||ii.loc_code||' set fname = replace(fname,''5'',''FIVE''),'||' lname = replace(lname,''5'',''FIVE'')';
        EXECUTE l_sql;

        l_sql := 'Update VOTERS'||ii.loc_code||' set fname = replace(fname,''6'',''SIX''),'||' lname = replace(lname,''6'',''SIX'')';
        EXECUTE l_sql;

        l_sql := 'Update VOTERS'||ii.loc_code||' set fname = replace(fname,''7'',''SEVEN''),'||' lname = replace(lname,''7'',''SEVEN'')';
        EXECUTE l_sql;

        l_sql := 'Update VOTERS'||ii.loc_code||' set fname = replace(fname,''8'',''EIGHT''),'||' lname = replace(lname,''8'',''EIGHT'')';
        EXECUTE l_sql;

        l_sql := 'Update VOTERS'||ii.loc_code||' set fname = replace(fname,''9'',''NINE''),'||' lname = replace(lname,''9'',''NINE'')';
        EXECUTE l_sql;

        l_sql := 'Update VOTERS'||ii.loc_code||' set fname = replace(fname,''0'',''ZERO''),'||' lname = replace(lname,''0'',''ZERO'')';
        EXECUTE l_sql;

     END LOOP;

     commit;

   EXCEPTION
     when others then
     rollback;
	   raise;

  END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE reset_refresh_voters (p_loc_code text ) FROM PUBLIC;
