-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = JUROR,public;




CREATE OR REPLACE PROCEDURE court_phoenix_populate_court_checks (l_part_no text, l_user text) AS $body$
DECLARE
  l_court_juror POOL%ROWTYPE;
  l_pool_no bigint;
  l_fname varchar(20);
  l_middle_name varchar(20);
  l_sur_name varchar(20);
  l_zip varchar(20);
  l_dob timestamp(0);
  lc_Job_Type text := 'court_phoenix_POPUALTE_COURT_CHECKS';

BEGIN
 /** Get data from pool table to juror */

  select *
  into STRICT l_court_juror
  from pool 
  where part_no = l_part_no
  and    is_active = 'Y';
  /** store data in local variables */

  l_pool_no := l_court_juror.pool_no;
  l_sur_name := l_court_juror.lname;
  l_fname := l_court_juror.fname;
  l_middle_name := l_fname;
  l_dob := l_court_juror.dob;
  l_zip := l_court_juror.zip;

  /** Parse name */
 
   IF ( ( l_fname is NULL ) OR ( l_sur_name is NULL ) ) THEN
		 CALL court_phoenix_write_error('Juror ' || l_part_no || ' contains null data');
            ELSE
            /***** BUG: If name is null error is generated, but insert runs anyway *****/

	   BEGIN
			l_fname := court_phoenix_jurorFirstName( replace(replace(regexp_replace(l_fname,'[ ]+',' ', 'g'),' -','-'),'- ','-'));
      l_middle_name := court_phoenix_jurorMiddleName( replace(replace(regexp_replace(l_middle_name,'[ ]+',' ', 'g'),' -','-'),'- ','-') );
      l_sur_name := court_phoenix_jurorSurname( replace(replace(regexp_replace(l_sur_name,'[ ]+',' ', 'g'),' -','-'),'- ','-') );

      /** insert rows to court_police_checks ready for phoenix run */

      insert into juror_court_police_check(id,
                               	surname,
                               	first_name,
                                last_name,
                               	postcode,
                               	dob,
                               	disqualified,
                               	check_complete,
                                try_count)
           values (l_part_no,
                   l_sur_name,
                   l_fname,
                   l_middle_name,
                   UPPER(replace(l_zip, ' ' , '')),
                   l_dob,
                   'N','N',0);
               		
            	EXCEPTION
               		WHEN OTHERS THEN
                	CALL court_phoenix_write_error( 'Error on writing '|| l_part_no || ' to juror table for checking ');
			            ROLLBACK;
			            RAISE;
            	END;
	    /*END IF;
      --END;*/
  
      /** insert rows to part_hist for history */
      insert into part_hist(part_no,
                       		date_part,
                    	  	history_code,
                       		user_id,
                       		other_information,
                       		pool_no)
           values (l_part_no,
                       		clock_timestamp(),
                       		'POLE',
                       		l_user,
                       		'Check Requested',
                       		l_pool_no);

   /** Update pool table + phoenix_date
   -- Note: owner included in where clause by Oracle becuase context is already set */
     update pool
	   set phoenix_date = trunc(sysdate),
	   police_check = 'E',
    	   user_EDTQ = l_user
	   where part_no = l_part_no
	   and is_active = 'Y'; 
  
    END IF; /** End if on null names */
        
          --COMMIT; --Removed as app will perform commit
          EXCEPTION
            when others then
	          CALL court_phoenix_write_error(sqlerrm);
     	      rollback;
	          raise;
END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE court_phoenix_populate_court_checks (l_part_no text, l_user text) FROM PUBLIC;
