-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW disq_lett (owner, juror_number, disq_code, date_disq, date_printed, printed) AS SELECT
    d.OWNER,
    d.PART_NO AS JUROR_NUMBER,
    d.DISQ_CODE,
    d.DATE_DISQ,
    d.DATE_PRINTED,
    d.PRINTED
  FROM
    JUROR.DISQ_LETT d
  WHERE
    d.OWNER = '400';

