-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW password (owner, login, password, last_used, user_level, aramis_auth_code, aramis_max_auth, password_changed_date, login_enabled_yn) AS SELECT
    p.owner,
    p.login,
    p.password,
    p.last_used,
    p.user_level,
    p.aramis_auth_code,
    p.aramis_max_auth,
    p.password_changed_date,
    p.login_enabled_yn
  FROM JUROR.PASSWORD p
  WHERE p.owner = '400';

