-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW pool_type (pool_type, pool_type_desc) AS SELECT
	pt.POOL_TYPE,
	pt.POOL_TYPE_DESC
  FROM
	JUROR.POOL_TYPE pt;

