-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW pool_stats (pool_no, total_summoned, court_supply, available, unavailable, unresolved) AS SELECT 		pm.POOL_NO,
			SUM(CASE WHEN pm.OWNER = '400' THEN 1 ELSE 0 END) AS TOTAL_SUMMONED,
			SUM(CASE WHEN pm.OWNER <> '400' AND pm.IS_ACTIVE = 'Y' THEN 1 ELSE 0 END) AS COURT_SUPPLY,
			SUM(CASE WHEN pm.OWNER = '400' AND pm.STATUS = 2 THEN 1 ELSE 0 END) AS AVAILABLE,
			SUM(CASE WHEN pm.OWNER = '400' AND pm.STATUS NOT IN (1, 2, 11) THEN 1 ELSE 0 END) AS UNAVAILABLE,
			SUM(CASE WHEN pm.OWNER = '400' AND pm.STATUS IN (1, 11) THEN 1 ELSE 0 END) AS UNRESOLVED
FROM		JUROR_DIGITAL_USER.POOL_MEMBER pm
WHERE       pm.SUMMONS_FILE IS NULL OR pm.SUMMONS_FILE <> 'Disq. on selection' -- Exclude disqualified on selection records
GROUP BY	POOL_NO;

