-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW print_files (printfile_name, creation_date, form_type, detail_rec, extracted_flag, part_no, digital_comms) AS SELECT
    P.PRINTFILE_NAME,
    P.CREATION_DATE,
    P.FORM_TYPE,
    P.DETAIL_REC,
    P.EXTRACTED_FLAG,
    P.PART_NO,
    P.DIGITAL_COMMS
  FROM
    JUROR.PRINT_FILES P;

