-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW print_files_notify_comms (printfile_name, creation_date, form_type, detail_rec, extracted_flag, juror_number, digital_comms, template_id, template_name, notify_name, h_email) AS SELECT
    P.PRINTFILE_NAME,
    P.CREATION_DATE,
    P.FORM_TYPE,
    P.DETAIL_REC,
    P.EXTRACTED_FLAG,
    P.PART_NO           AS JUROR_NUMBER,
    P.DIGITAL_COMMS,
    N.TEMPLATE_ID,
    N.TEMPLATE_NAME,
    N.NOTIFY_NAME,
    J.H_EMAIL
  FROM
    JUROR.PRINT_FILES P,
    JUROR_DIGITAL.NOTIFY_TEMPLATE_MAPPING N,
    JUROR.POOL J
  WHERE
    P.FORM_TYPE = N.FORM_TYPE
    AND P.PART_NO = J.PART_NO
    AND P.CREATION_DATE > date_trunc('day', statement_timestamp() - make_interval(days := CAST(coalesce((SELECT VALUE FROM juror_digital.app_settings WHERE setting ='PRINT_FILES_BACKFILL_DAYS'),'3') as INTEGER)))
    AND P.DIGITAL_COMMS = 'N'
    AND N.NOTIFICATION_TYPE = 1
    AND J.OWNER = '400'
    AND J.IS_ACTIVE = 'Y'
    AND trim(both J.H_EMAIL) IS NOT NULL;

