-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW stats_response_times_totals (all_responses_total, online_responses_total) AS SELECT
sum(coalesce(S.response_count,0)) AS ALL_RESPONSES_TOTAL,
SUM(case when S.response_method = 'Online' THEN coalesce(S.response_count,0) ELSE 0 END) AS ONLINE_RESPONSES_TOTAL
FROM
JUROR_DIGITAL.STATS_RESPONSE_TIMES S;

