-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror,public;
\set ON_ERROR_STOP ON

\i ./schema/functions/ARAMIS_INVOICE_NUMBER_NEXTVAL_function.sql
\i ./schema/functions/ARAMIS_UNIQUE_ID_NEXTVAL_function.sql
\i ./schema/functions/ATTEND_AUDIT_NUMBER_NEXTVAL_function.sql
\i ./schema/functions/AUDIT_NUMBER_NEXTVAL_function.sql
\i ./schema/functions/BUREAU_ONLY_function.sql
\i ./schema/functions/GET_POOL_COMMENTS_function.sql
\i ./schema/functions/GET_VOTERS_function.sql
\i ./schema/functions/LOCAL_PART_NO_NEXTVAL_function.sql
\i ./schema/functions/RESTRICT_COURT_function.sql
\i ./schema/functions/RETURN_OWNER_function.sql
\i ./schema/functions/SET_UP_VOTERS_function.sql
