-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = JUROR,public;




-----------------------------------------------------------------------------------
--  Function: pkg_crypto_get_hash(pin_string)
--
--  Parms in: pin_string - string for which hash value is required
--
--  Returns:  HASH value of fixed length
--
--  Description
--  ===========
--  Returns fixed length HASH value for specified string.
--
--  History
--
--	Version Name		  Date		 Desc
--	======= ========= ======== ====
--	V1.0    Kal Sohal 05/06/07 Initial version
-----------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pkg_crypto_get_hash (pin_string text) RETURNS varchar AS $body$
BEGIN
      Return pkg_crypto_get_hash(pin_string, 200);
    EXCEPTION
      WHEN OTHERS THEN
           RAISE EXCEPTION '%', 'pck_crypto.get_hash()  SQLcode = ' || SQLSTATE || ' SQLErrm = ' || SQLERRM USING ERRCODE = '45000' /* code was: -2000 */;
           RETURN NULL;
    END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION pkg_crypto_get_hash (pin_string text) FROM PUBLIC;
