-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.2;sid=xe;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET search_path = hk,public;
ALTER TABLE hk_owner_restrict ALTER COLUMN ID SET NOT NULL;
ALTER TABLE hk_owner_restrict ALTER COLUMN DESCRIPTION SET NOT NULL;
ALTER TABLE hk_owner_restrict ALTER COLUMN VALUE SET NOT NULL;
ALTER TABLE hk_owner_restrict ALTER COLUMN LAST_UPDATED SET NOT NULL;
-- ALTER TABLE hk_params ADD PRIMARY KEY ("key");
ALTER TABLE hk_params ALTER COLUMN LAST_UPDATED SET NOT NULL;
