-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.2;sid=xe;port=1521

SET client_encoding TO 'UTF8';

-- \set ON_ERROR_STOP ON - UNCOMMENT LATER!

do
$$
begin
  if not exists (select * from pg_user where usename = 'hk') then
     CREATE ROLE HK WITH PASSWORD 'postgres' LOGIN;
  end if;
end
$$
;

CREATE SCHEMA IF NOT EXISTS hk;
ALTER SCHEMA hk OWNER TO hk;

SET search_path = hk,public;


CREATE TABLE hk_owner_restrict (
	id numeric(38) NOT NULL,
	description varchar(60) NOT NULL,
	value varchar(3) NOT NULL,
	last_updated timestamp(0) NOT NULL
) ;


CREATE TABLE hk_params (
	"key" numeric(38) NOT NULL,
	"value" varchar(20),
	description varchar(60),
	last_updated timestamp(0) NOT NULL
) ;
