-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.2;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = hk,public;
\set ON_ERROR_STOP ON



-- Oracle package 'HOUSEKEEPING' declaration, please edit to match PostgreSQL syntax.


-- \i ./schema/packages/housekeeping/housekeeping_write_params_to_log_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_fetch_parameters_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_initate_log_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_close_log_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_record_internal_log_start_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_write_child_rowcounts_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_write_footer_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_row_counts_juror_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_check_time_expired_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_audit_report_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_part_hist_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_part_expenses_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_cert_lett_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_disq_lett_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_manuals_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_confirm_lett_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_part_amendments_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_exc_denied_lett_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_def_lett_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_def_denied_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_defer_dbf_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_undeliver_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_exc_lett_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_phone_log_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_request_lett_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_fta_lett_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_postpone_lett_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_pool_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_panel_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_sa_abaccus_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_sa_attendance_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_sa_content_store_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_sa_error_log_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_sa_holidays_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_sa_print_files_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_sa_pl_xml_status_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_sa_coroner_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_sa_module_machine_xref_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_sa_peak_usage_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_delete_sa_aramis_payments_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_parent_delete_trial_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_parent_delete_unique_pool_package.sql
-- \i ./schema/packages/housekeeping/housekeeping_report_error_package.sql

-- End of Oracle package 'HOUSEKEEPING' declaration



-- Oracle package 'HOUSEKEEPING_NOCOMMIT' declaration, please edit to match PostgreSQL syntax.


-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_write_params_to_log_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_fetch_parameters_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_initate_log_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_close_log_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_record_internal_log_start_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_write_child_rowcounts_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_write_footer_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_row_counts_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_check_time_expired_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_audit_report_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_part_hist_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_part_expenses_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_cert_lett_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_disq_lett_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_manuals_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_confirm_lett_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_part_amendments_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_exc_denied_lett_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_def_lett_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_def_denied_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_defer_dbf_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_undeliver_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_exc_lett_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_phone_log_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_request_lett_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_fta_lett_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_postpone_lett_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_pool_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_panel_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_sa_abaccus_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_sa_attendance_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_sa_content_store_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_sa_error_log_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_sa_holidays_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_sa_print_files_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_sa_pl_xml_status_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_sa_coroner_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_sa_module_machine_xref_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_sa_peak_usage_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_delete_sa_aramis_payments_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_parent_delete_trial_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_parent_delete_unique_pool_package.sql
-- \i ./schema/packages/housekeeping_nocommit/housekeeping_nocommit_report_error_package.sql

-- End of Oracle package 'HOUSEKEEPING_NOCOMMIT' declaration



-- Oracle package 'JUROR_DIGITAL_HOUSEKEEPING' declaration, please edit to match PostgreSQL syntax.


\i ./schema/packages/juror_digital_housekeeping/juror_digital_housekeeping_delete_juror_responses_aud_package.sql
\i ./schema/packages/juror_digital_housekeeping/juror_digital_housekeeping_del_juror_resp_cjs_employment_package.sql
\i ./schema/packages/juror_digital_housekeeping/juror_digital_housekeeping_del_juror_resp_special_needs_package.sql
\i ./schema/packages/juror_digital_housekeeping/juror_digital_housekeeping_delete_change_log_item_package.sql
\i ./schema/packages/juror_digital_housekeeping/juror_digital_housekeeping_delete_change_log_package.sql
\i ./schema/packages/juror_digital_housekeeping/juror_digital_housekeeping_del_staff_juror_response_audit_package.sql
\i ./schema/packages/juror_digital_housekeeping/juror_digital_housekeeping_delete_juror_response_package.sql
\i ./schema/packages/juror_digital_housekeeping/juror_digital_housekeeping_write_audit_package.sql
\i ./schema/packages/juror_digital_housekeeping/juror_digital_housekeeping_perform_deletions_package.sql

-- End of Oracle package 'JUROR_DIGITAL_HOUSEKEEPING' declaration

