-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.4;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital,public;
\set ON_ERROR_STOP ON

PROCEDURE               reset_seq(p_name IN VARCHAR2, p_val IN NUMBER) 
AS
  l_num NUMBER;
  BEGIN
    EXECUTE IMMEDIATE 'select ' || p_name || '.nextval from dual' INTO l_num;
    IF (p_val - l_num - 1) != 0
      THEN
        EXECUTE IMMEDIATE 'alter sequence ' || p_name || ' increment by ' || (p_val - l_num - 1) || ' minvalue 0';
    END IF;
    EXECUTE IMMEDIATE 'select ' || p_name || '.nextval from dual' INTO l_num;
    EXECUTE IMMEDIATE 'alter sequence ' || p_name || ' increment by 1 ';
  END;

