-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = JUROR,public;




CREATE OR REPLACE PROCEDURE printfiles_to_clob_extract (p_limit bigint default 1000000) AS $body$
DECLARE


c1 CURSOR FOR SELECT * FROM FORM_ATTR;

l_form_type text;
l_max_rec_len bigint;

BEGIN
 	OPEN c1;
 	LOOP
			FETCH c1 into l_form_type, l_max_rec_len;
 			PERFORM set_config('printfiles_to_clob_g_limit', p_limit, false);
		     -- Write deatils into flat file
			  begin
		    		PERFORM write_to_clob( l_form_type, l_max_rec_len);
			  end;
	END LOOP;
commit;

EXCEPTION
	WHEN OTHERS THEN
	    rollback;
		RAISE NOTICE 'Rollback';
		RAISE EXCEPTION '%', 'Error in Extract Procedure' USING ERRCODE = '45008';
		raise;

END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE printfiles_to_clob_extract (p_limit bigint default 1000000) FROM PUBLIC;
