-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.4;sid=xe;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE SCHEMA IF NOT EXISTS juror;

create user juror WITH password 'postgres' login;
ALTER SCHEMA juror OWNER TO juror;

SET search_path = juror,public;


CREATE TABLE abaccus (
	form_type varchar(6) NOT NULL,
	loc_code varchar(3) NOT NULL,
	creation_date timestamp(0) NOT NULL,
	number_of_items integer
) ;


CREATE TABLE acct_pay_data (
	owner varchar(3) DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	voter_reg varchar(12),
	days double precision NOT NULL,
	net_pay decimal(22,2),
	ssn varchar(11),
	address varchar(40) NOT NULL,
	zip varchar(10),
	pool_no varchar(9) NOT NULL,
	date_acct timestamp(0) NOT NULL,
	faudit varchar(11),
	state varchar(2),
	start_date_of_service timestamp(0),
	pool_type varchar(3),
	miles numeric(38),
	no_mileage_days numeric(38),
	county_phone_no varchar(12),
	lname varchar(20),
	fname varchar(20),
	county_code varchar(5)
) ;


CREATE TABLE accused (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	trial_no varchar(16) NOT NULL,
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL
) ;


CREATE TABLE appearances (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	att_date timestamp(0) NOT NULL,
	faudit varchar(11),
	cheque_no varchar(10),
	court_emp varchar(1),
	timein timestamp(0),
	timeout timestamp(0),
	pool_trial_no varchar(16),
	audits varchar(11),
	amount double precision,
	reason varchar(1),
	app_stage smallint,
	pay_county_emp varchar(1),
	loc_code varchar(3) NOT NULL,
	pay_expenses varchar(1),
	date_paid timestamp(0),
	donation_code varchar(4),
	non_attendance varchar(1)
) WITH (fillfactor=60);


CREATE TABLE aramis_payments (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	loc_code varchar(3) NOT NULL,
	unique_id varchar(7) NOT NULL,
	creation_date timestamp(0) NOT NULL DEFAULT statement_timestamp(),
	expense_total double precision NOT NULL,
	part_invoice varchar(16) NOT NULL,
	bank_sort_code varchar(6),
	bank_ac_name varchar(18),
	bank_ac_number varchar(8),
	build_soc_number varchar(18),
	address_line1 varchar(35),
	address_line2 varchar(35),
	address_line3 varchar(35),
	address_line4 varchar(35),
	address_line5 varchar(35),
	postcode varchar(10),
	aramis_auth_code varchar(9) NOT NULL,
	name varchar(50) NOT NULL,
	loc_cost_centre varchar(5) NOT NULL,
	travel_total double precision,
	sub_total double precision,
	floss_total double precision,
	sub_date timestamp(0) NOT NULL,
	con_file_ref varchar(30)
) ;


CREATE TABLE attendance (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	month_start timestamp(0) NOT NULL,
	loc_code varchar(3) NOT NULL,
	available_days integer,
	attendance_days integer,
	sitting_days integer,
	no_trials integer,
	last_update timestamp(0)
) ;


CREATE TABLE audit_f_report (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	faudit varchar(11) NOT NULL,
	line_no bigint NOT NULL,
	part_no varchar(9) NOT NULL,
	pool_trial_no varchar(16),
	reason varchar(1),
	total_amount double precision,
	amount double precision,
	att_date timestamp(0),
	lname varchar(20),
	is_active varchar(1),
	fname varchar(20),
	cheque_no varchar(10),
	date_paid timestamp(0),
	address varchar(40),
	city varchar(20),
	state varchar(2),
	zip varchar(10),
	pay_county varchar(1),
	donation_code varchar(4),
	address1 varchar(35),
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	postcode varchar(10),
	total_travel double precision,
	total_subsistance double precision,
	total_loss_of_earnings double precision,
	travel_code varchar(13),
	subsistence_code varchar(13),
	loss_of_earnings_code varchar(13),
	amt_spent double precision,
	user_id varchar(20),
	loc_code varchar(3),
	loc_rate_mcycles double precision,
	loc_rate_mcars double precision,
	loc_rate_pcycles double precision,
	loc_standard_mcycles double precision,
	loc_standard_mcars double precision,
	loc_loss_lfour double precision,
	loc_loss_mfour double precision,
	loc_loss_mten double precision,
	loc_subs_lfive double precision,
	loc_subs_mfive double precision,
	loc_loss_oten double precision,
	loc_loss_overnight double precision,
	loc_child_care double precision,
	loc_misc_amount double precision,
	loc_rail_bus double precision,
	loc_hired_vehicle double precision,
	loc_rate_mcycles_2 double precision,
	loc_rate_mcars_2 double precision,
	loc_rate_mcars_3 double precision,
	loc_loss_on_half double precision,
	loc_ac_loss_of_earn varchar(13),
	loc_ac_subst varchar(13),
	loc_ac_travel varchar(13),
	loc_cost_centre varchar(7),
	report_type varchar(30),
	default_mileage numeric(38),
	default_paid_cash varchar(1),
	default_travel_time real,
	default_financial_loss double precision,
	default_amt_spent double precision,
	smart_card varchar(20),
	sort_code varchar(6),
	bank_acct_name varchar(18),
	bank_acct_no varchar(8),
	bldg_soc_roll_no varchar(18)
) ;


CREATE TABLE audit_report (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	audits varchar(11) NOT NULL,
	line_no numeric(38) NOT NULL,
	part_no varchar(9) NOT NULL,
	timein timestamp(0),
	timeout timestamp(0),
	pool_trial varchar(16),
	reason varchar(1),
	pay_county varchar(1),
	mileage numeric(38),
	mileage_rate double precision,
	total_mileage double precision,
	public_parking double precision,
	public_trans double precision,
	child_care double precision,
	misc_description varchar(20),
	misc_amount double precision,
	total_amount double precision,
	amount double precision,
	court_emp varchar(1),
	att_date timestamp(0),
	lname varchar(20),
	is_active varchar(1),
	loc_code varchar(3),
	fname varchar(20),
	app_stage numeric(38),
	donation_code varchar(4),
	public_parking_total double precision,
	rail_bus_total double precision,
	hired_vehicle_total double precision,
	rate_mcycles double precision,
	mcycles_pass smallint,
	mcycles_total double precision,
	mcars_pass smallint,
	rate_mcars double precision,
	mcars_total double precision,
	rate_pcycles double precision,
	pcycles_total double precision,
	los_lfour_total double precision,
	los_mfour_total double precision,
	loss_mten_total double precision,
	subs_lfive_total double precision,
	subs_mfive_total double precision,
	loss_oten_total double precision,
	loss_oten_h_total double precision,
	loss_overnight_total double precision,
	amt_spent double precision,
	travel_time real,
	daily_time real,
	total_time real,
	non_attendance varchar(1),
	date_aramis_created timestamp(0),
	aramis_created varchar(1),
	exp_subs_date timestamp(0),
	mod_date timestamp(0),
	difference double precision,
	new_total double precision,
	pay_cash varchar(1),
	user_id varchar(20)
) ;


CREATE TABLE bioform (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	county varchar(18),
	live_st numeric(38),
	live_ct numeric(38),
	educ_yrs numeric(38),
	birth_st varchar(2),
	birth_cit varchar(16),
	num_children numeric(38),
	child_boy numeric(38),
	age_boy numeric(38),
	child_gir numeric(38),
	age_gir numeric(38),
	marital varchar(1),
	can_drive varchar(1),
	crim_case varchar(1),
	convicted varchar(1),
	conv_exp varchar(29),
	emp_name varchar(20),
	emp_add varchar(20),
	emp_city varchar(16),
	years_worked numeric(38),
	spouse_oc varchar(18),
	lawsuit varchar(1),
	type_suit varchar(20),
	injuries varchar(1),
	p_bodily varchar(1),
	f_bodily varchar(1),
	was_juror varchar(1),
	civ_or_crim varchar(1),
	jury_date timestamp(0),
	court varchar(16),
	spouse_name varchar(40),
	spouse_emp varchar(20),
	spouse_emp_yr numeric(38),
	religion varchar(20),
	jury_verdict varchar(1),
	friends_law varchar(1),
	boy_ages varchar(14),
	girl_ages varchar(14),
	jury_year varchar(2),
	was_juror_c varchar(1),
	jury_year_c varchar(2),
	jury_verdict_c varchar(10),
	allstate varchar(1),
	statefarm varchar(1),
	otherins varchar(20)
) ;


CREATE TABLE cert_lett (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	printed varchar(1),
	date_printed timestamp(0)
) ;


CREATE TABLE condition (
	condition_id bigint NOT NULL,
	description varchar(150) NOT NULL,
	qual_literal varchar(3),
	ql_use_flag varchar(1),
	ql_modifier varchar(1),
	duration varchar(3),
	duration_modifier varchar(1),
	end_date_period varchar(3)
) ;


CREATE TABLE confirm_lett (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	printed varchar(1),
	date_printed timestamp(0)
) ;


CREATE TABLE contact_preference (
	id smallint,
	type varchar(25),
	description varchar(50)
) ;


CREATE TABLE content_store (
	request_id bigint,
	document_id varchar(50) NOT NULL,
	date_on_q_for_send timestamp(0) DEFAULT statement_timestamp(),
	file_type varchar(10) NOT NULL,
	date_sent timestamp(0),
	data text
) ;


CREATE TABLE context_data (
	loc_code varchar(3) NOT NULL,
	context_id varchar(3)
) ;


CREATE TABLE coroner_pool (
	cor_pool_no varchar(9) NOT NULL,
	cor_name varchar(35) NOT NULL,
	cor_court_loc varchar(3) NOT NULL,
	cor_request_dt timestamp(0) NOT NULL,
	cor_service_dt timestamp(0) NOT NULL,
	cor_no_requested integer NOT NULL
) ;


CREATE TABLE coroner_pool_detail (
	cor_pool_no varchar(9) NOT NULL,
	part_no varchar(9) NOT NULL,
	title varchar(10),
	fname varchar(20) NOT NULL,
	lname varchar(20) NOT NULL,
	address1 varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	postcode varchar(10)
) ;


CREATE TABLE court_catchment_area (
	postcode varchar(4) NOT NULL,
	loc_code varchar(3) NOT NULL
) ;


CREATE TABLE court_group (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	group_no smallint NOT NULL,
	name varchar(40)
) ;


CREATE TABLE court_location (
	owner varchar(3) DEFAULT current_setting('juror_app.owner', true),
	loc_code varchar(3) NOT NULL,
	loc_name varchar(40) NOT NULL,
	loc_address1 varchar(35) NOT NULL,
	loc_address2 varchar(35),
	loc_address3 varchar(35),
	loc_address4 varchar(35),
	loc_address5 varchar(35),
	loc_address6 varchar(35),
	loc_zip varchar(10),
	loc_phone varchar(12),
	call_in_phone varchar(12),
	tdd_phone varchar(12),
	loc_court_name varchar(30),
	loc_room_no varchar(6),
	loc_attend_time varchar(10),
	loc_rate_mcycles double precision,
	loc_rate_mcars double precision,
	loc_rate_pcycles double precision,
	loc_standard_mcycles double precision,
	loc_standard_mcars double precision,
	loc_loss_lfour double precision,
	loc_loss_mfour double precision,
	loc_loss_mten double precision,
	loc_subs_lfive double precision,
	loc_subs_mfive double precision,
	loc_loss_oten double precision,
	loc_loss_overnight double precision,
	loc_child_care double precision,
	loc_misc_description varchar(20),
	loc_misc_amount double precision,
	check_for_bioform varchar(1),
	loc_default_room varchar(6),
	loc_ins_hour_rate double precision,
	loc_deferred_perc bigint,
	loc_signature varchar(30),
	loc_timeout timestamp(0),
	loc_pet_months numeric(38),
	term_of_service varchar(20),
	county_code varchar(5),
	loc_jury_rate_n numeric(38),
	voters_count integer,
	loc_rail_bus double precision,
	loc_hired_vehicle double precision,
	loc_rate_mcycles_2 double precision,
	loc_rate_mcars_2 double precision,
	loc_rate_mcars_3 double precision,
	loc_loss_on_half double precision,
	loc_ac_loss_of_earn varchar(13),
	loc_ac_subst varchar(13),
	loc_ac_travel varchar(13),
	loc_cost_centre varchar(7),
	loc_primary varchar(1),
	group_no smallint,
	voters_lock smallint,
	last_update timestamp(0),
	yield double precision,
	loc_rate_mcycles_alt double precision,
	loc_rate_mcars_alt double precision,
	loc_rate_pcycles_alt double precision,
	loc_loss_lfour_alt double precision,
	loc_loss_mfour_alt double precision,
	loc_loss_mten_alt double precision,
	loc_subs_lfive_alt double precision,
	loc_subs_mfive_alt double precision,
	loc_loss_oten_alt double precision,
	loc_loss_overnight_alt double precision,
	loc_child_care_alt double precision,
	loc_rail_bus_alt double precision,
	loc_hired_vehicle_alt double precision,
	loc_rate_mcycles_2_alt double precision,
	loc_rate_mcars_2_alt double precision,
	loc_rate_mcars_3_alt double precision,
	loc_loss_on_half_alt double precision,
	loc_rate_transition timestamp(0),
	pnc_check_on varchar(1),
	catering_scheme varchar(1) DEFAULT 'N',
	export_max_rows integer,
	export_path varchar(200),
	pool_transfer_adjustment_days bigint DEFAULT 0,
	location_address varchar(230),
	jury_officer_phone varchar(100),
	region_id varchar(5)
) ;


CREATE TABLE current_trans (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	login varchar(20) NOT NULL,
	trial_no varchar(16) NOT NULL,
	room_no varchar(6),
	judge varchar(4),
	panel_total numeric(38),
	panel_remaining numeric(38),
	scheduled_today numeric(38),
	checked_in numeric(38),
	record_type varchar(1),
	hdr_scheduled numeric(38),
	hdr_checked_in numeric(38),
	hdr_checked_out numeric(38),
	hdr_in_court numeric(38),
	hdr_available numeric(38),
	hdr_never_served numeric(38)
) ;


CREATE TABLE daily_trans (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	unique_id varchar(20) NOT NULL,
	trial varchar(16) NOT NULL,
	room varchar(6),
	judge varchar(4),
	max_used numeric(38),
	used_now numeric(38),
	scheduled numeric(38),
	in_court numeric(38)
) ;


CREATE TABLE db_version (
	component varchar(256) NOT NULL,
	latest_version varchar(8) NOT NULL,
	min_version varchar(8)
) ;


CREATE TABLE defer_dbf (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	defer_to timestamp(0) NOT NULL,
	checked varchar(1),
	loc_code varchar(3) NOT NULL
) ;


CREATE TABLE def_denied (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	date_def timestamp(0) NOT NULL,
	exc_code varchar(1) NOT NULL,
	printed varchar(1),
	date_printed timestamp(0)
) ;


CREATE TABLE def_lett (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	date_def timestamp(0) NOT NULL,
	exc_code varchar(1) NOT NULL,
	printed varchar(1),
	date_printed timestamp(0)
) ;


CREATE TABLE disposal_condition (
	condition_id bigint NOT NULL,
	disposal_id bigint NOT NULL
) ;


CREATE TABLE disposition (
	disposition_code varchar(3) NOT NULL,
	description varchar(30) NOT NULL
) ;


CREATE TABLE disq_lett (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	disq_code varchar(1) NOT NULL,
	date_disq timestamp(0) NOT NULL,
	date_printed timestamp(0),
	printed varchar(1)
) ;


CREATE TABLE district (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	tcode varchar(3) NOT NULL,
	tname varchar(30),
	tcheck numeric(38)
) ;


CREATE TABLE dis_code (
	disq_code varchar(1) NOT NULL,
	description varchar(60) NOT NULL,
	enabled varchar(1)
) ;


CREATE TABLE error_log (
	time_stamp timestamp(0) DEFAULT statement_timestamp(),
	job varchar(50),
	error_info varchar(100)
) ;


CREATE TABLE exc_code (
	exc_code varchar(1) NOT NULL,
	description varchar(60) NOT NULL,
	by_right varchar(1),
	enabled varchar(1)
) ;


CREATE TABLE exc_denied_lett (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	date_excused timestamp(0) NOT NULL,
	exc_code varchar(1),
	printed varchar(1),
	date_printed timestamp(0)
) ;


CREATE TABLE exc_lett (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	date_excused timestamp(0) NOT NULL,
	exc_code varchar(1),
	printed varchar(1),
	date_printed timestamp(0)
) ;


CREATE TABLE export_placeholders (
	placeholder_name varchar(48) NOT NULL,
	source_table_name varchar(48) NOT NULL,
	source_column_name varchar(48) NOT NULL,
	type varchar(12) NOT NULL,
	description varchar(100),
	default_value varchar(200),
	editable varchar(1),
	validation_rule varchar(600),
	validation_message varchar(200),
	validation_format varchar(60)
) ;


CREATE TABLE first_juror_digital_pool (
	loc_code varchar(3),
	pool_no varchar(9),
	date_created timestamp(0)
) ;


CREATE TABLE forms_list (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	doc_name varchar(8) NOT NULL,
	description varchar(30),
	path_name varchar(40),
	word_program varchar(40)
) ;


CREATE TABLE form_attr (
	form_type varchar(6) NOT NULL,
	dir_name varchar(20) NOT NULL,
	max_rec_len bigint
) ;


CREATE TABLE fta_lett (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	date_fta timestamp(0) NOT NULL,
	d_selected timestamp(0) NOT NULL,
	printed varchar(1),
	date_printed timestamp(0),
	no_show_printed varchar(1),
	no_show_date_printed timestamp(0)
) ;


CREATE TABLE hk_run_log (
	seq_id numeric(38),
	start_time timestamp(0),
	end_time timestamp(0),
	jurors_deleted numeric(38),
	jurors_error numeric(38),
	return_code numeric(38)
) ;


CREATE TABLE holidays (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	holiday timestamp(0) NOT NULL,
	description varchar(30) NOT NULL
) ;


CREATE TABLE ineligible_code (
	disposal_code bigint NOT NULL,
	description varchar(150) NOT NULL
) ;


CREATE TABLE judge (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	judge varchar(4) NOT NULL,
	description varchar(30) NOT NULL,
	seating_plan numeric(38),
	tel_no varchar(16),
	room char(6)
) ;


CREATE TABLE juror (
	id varchar(9) NOT NULL,
	surname varchar(20) NOT NULL,
	first_name varchar(20) NOT NULL,
	last_name varchar(20),
	dob timestamp(0) NOT NULL,
	postcode varchar(8) NOT NULL,
	check_complete varchar(1),
	disqualified varchar(1),
	try_count smallint
) ;


CREATE TABLE juror_court_police_check (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	id varchar(9) NOT NULL,
	surname varchar(20) NOT NULL,
	first_name varchar(20) NOT NULL,
	last_name varchar(20),
	dob timestamp(0) NOT NULL,
	postcode varchar(8) NOT NULL,
	check_complete varchar(1),
	disqualified varchar(1),
	try_count smallint
) ;


CREATE TABLE juror_tables (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	pb_table_name varchar(30) NOT NULL,
	description varchar(30) NOT NULL,
	internal varchar(1) NOT NULL,
	pb_edit_dw_name varchar(30) NOT NULL,
	pb_report_dw_name varchar(30),
	pb_report_dw_orient varchar(1),
	select_enable varchar(1),
	edit_enable varchar(1),
	insert_enable varchar(1),
	delete_enable varchar(1)
) ;


CREATE TABLE location (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	location varchar(6) NOT NULL,
	description varchar(30) NOT NULL
) ;


CREATE TABLE manuals (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no char(9) NOT NULL,
	pool_no char(9) NOT NULL,
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	title varchar(10),
	dob timestamp(0),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	h_phone varchar(15),
	w_phone varchar(15),
	m_phone varchar(15),
	w_ph_local char(4),
	mileage numeric(38),
	pool_seq char(4),
	pool_status numeric(38),
	is_active char(1),
	pool_type char(3),
	loc_code char(3),
	ret_date timestamp(0) NOT NULL,
	responded char(1) NOT NULL,
	reg_spc char(1) NOT NULL,
	next_date timestamp(0),
	on_call char(1),
	notes varchar(2000),
	status char(1),
	date_added timestamp(0) NOT NULL,
	added_by varchar(20),
	h_email varchar(254),
	contact_preference smallint DEFAULT 0
) ;


CREATE TABLE manuals_status (
	code char(1) NOT NULL,
	description varchar(60) NOT NULL
) ;


CREATE TABLE messages (
	part_no varchar(9) NOT NULL,
	file_datetime varchar(15) NOT NULL,
	username varchar(20) NOT NULL,
	loc_code varchar(3) NOT NULL,
	phone varchar(15),
	email varchar(254),
	loc_name varchar(100),
	pool_no varchar(9),
	subject varchar(50),
	message_text varchar(2000),
	message_id bigint NOT NULL,
	message_read varchar(2) DEFAULT 'NR'
) ;


CREATE TABLE module_machine_xref (
	machine_name varchar(24) NOT NULL,
	juror_user varchar(20) NOT NULL,
	module_name varchar(30) NOT NULL,
	release_number varchar(40),
	revision_no varchar(24),
	last_update timestamp(0)
) ;


CREATE TABLE new_dob (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	snum varchar(10) NOT NULL,
	not_known varchar(10),
	sin varchar(11),
	race varchar(1),
	gender varchar(1),
	dob timestamp(0),
	finitial varchar(1),
	sinitial varchar(1)
) ;


CREATE TABLE panel (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	trial_no varchar(16) NOT NULL,
	rand_no numeric(38),
	date_selected timestamp(0) NOT NULL,
	result char(2),
	complete varchar(1)
) ;


CREATE TABLE panel_group (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	pool_no varchar(9) NOT NULL,
	group_no varchar(3) NOT NULL
) ;


CREATE TABLE part_amendments (
	owner varchar(3) DEFAULT current_setting('juror_app.owner', true),
	part_no char(9) NOT NULL,
	edit_date timestamp(0) NOT NULL,
	edit_userid varchar(20) NOT NULL,
	title varchar(10),
	fname varchar(20),
	lname varchar(20),
	dob timestamp(0),
	address varchar(175),
	zip varchar(10),
	sort_code char(6),
	bank_acct_name varchar(18),
	bank_acct_no char(8),
	bldg_soc_roll_no varchar(18),
	pool_no char(9)
) ;


CREATE TABLE part_expenses (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	att_date timestamp(0) NOT NULL,
	number_atts smallint NOT NULL,
	end_date timestamp(0),
	mcycles_pass smallint,
	mcars_pass smallint,
	mileage smallint,
	mileage_rate double precision,
	total_mileage double precision,
	public_parking double precision,
	public_parking_days double precision,
	public_parking_total double precision,
	public_trans double precision,
	child_care double precision,
	child_care_rate double precision,
	child_care_days smallint,
	misc_description varchar(20),
	misc_amount double precision,
	total_amount double precision,
	rail_bus_days smallint,
	rail_bus double precision,
	rail_bus_total double precision,
	hired_vehicle_days smallint,
	hired_vehicle double precision,
	hired_vehicle_total double precision,
	mcycles_days smallint,
	rate_mcycles double precision,
	mcycles_total double precision,
	mcars_days smallint,
	rate_mcars double precision,
	mcars_total double precision,
	pcycles_days smallint,
	rate_pcycles double precision,
	pcycles_total double precision,
	std_mcycles_days smallint,
	std_mcycles double precision,
	std_mcycles_total double precision,
	std_mcars_days smallint,
	std_mcars double precision,
	std_mcars_total double precision,
	los_lfour_days smallint,
	loss_lfour double precision,
	los_lfour_total double precision,
	los_mfour_days smallint,
	loss_mfour double precision,
	los_mfour_total double precision,
	loss_mten_days smallint,
	loss_mten double precision,
	loss_mten_total double precision,
	subs_lfive_days smallint,
	subs_lfive double precision,
	subs_lfive_total double precision,
	subs_mfive_days smallint,
	subs_mfive double precision,
	subs_mfive_total double precision,
	loss_oten_days smallint,
	loss_oten double precision,
	loss_oten_total double precision,
	loss_oten_h_total double precision,
	loss_overnight_days double precision,
	loss_overnight double precision,
	loss_overnight_total double precision,
	amt_spent double precision,
	travel_time real,
	daily_time real,
	total_time real,
	non_attendance varchar(1),
	date_aramis_created timestamp(0),
	aramis_created varchar(1),
	exp_subs_date timestamp(0),
	pay_cash varchar(1),
	pay_accepted varchar(1),
	user_id varchar(20)
) WITH (fillfactor=40);


CREATE TABLE part_hist (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	date_part timestamp(0) NOT NULL,
	history_code varchar(4) NOT NULL,
	user_id varchar(20) NOT NULL,
	other_information varchar(27),
	pool_no varchar(9),
	last_update timestamp(0)
) ;


CREATE TABLE password (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	login varchar(20) NOT NULL,
	password varchar(20) NOT NULL,
	last_used timestamp(0),
	user_level varchar(1) NOT NULL,
	aramis_auth_code varchar(9),
	aramis_max_auth double precision,
	password_changed_date timestamp(0),
	login_enabled_yn varchar(1) DEFAULT 'Y'
) ;


CREATE TABLE password_export_placeholders (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	login varchar(20) NOT NULL,
	placeholder_name varchar(48) NOT NULL,
	use varchar(1)
) ;


CREATE TABLE peak_usage (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	vd_date timestamp(0) NOT NULL,
	no_attend numeric(38),
	peak_no numeric(38),
	no_scheduled numeric(38),
	no_panels numeric(38)
) ;


CREATE TABLE phoenix_temp (
	part_no varchar(9) NOT NULL,
	last_name varchar(20) NOT NULL,
	first_name varchar(20) NOT NULL,
	postcode varchar(10) NOT NULL,
	date_of_birth timestamp(0) NOT NULL,
	result varchar(1),
	checked varchar(1)
) ;


CREATE TABLE phone_log (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	user_id varchar(20) NOT NULL,
	start_call timestamp(0) NOT NULL,
	end_call timestamp(0),
	phone_code varchar(2) NOT NULL,
	notes varchar(2000),
	last_update timestamp(0)
) ;


CREATE TABLE pl_xml_status (
	sequence_no bigint NOT NULL,
	circuit_name varchar(100) NOT NULL,
	shell_circuit_id varchar(277) NOT NULL,
	date_time_stamp timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status varchar(1) NOT NULL
) ;


CREATE TABLE pnc_proxy (
	juror_id integer NOT NULL,
	disposal_code smallint,
	effective_date timestamp(0),
	qual_literal varchar(3),
	sentence_amount bigint,
	sentence_period varchar(3),
	on_bail varchar(1)
) ;


CREATE TABLE pool (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	pool_no varchar(9) NOT NULL,
	poll_number varchar(5),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	h_phone varchar(15),
	w_phone varchar(15),
	w_ph_local varchar(4),
	times_sel numeric(38),
	trial_no varchar(16),
	juror_no numeric(38),
	reg_spc varchar(1) NOT NULL,
	ret_date timestamp(0) NOT NULL,
	def_date timestamp(0),
	responded varchar(1) NOT NULL,
	date_excus timestamp(0),
	exc_code varchar(1),
	acc_exc varchar(1),
	date_disq timestamp(0),
	disq_code varchar(1),
	mileage numeric(38),
	location varchar(6),
	user_edtq varchar(20),
	status numeric(38),
	notes varchar(2000),
	no_attendances numeric(38),
	is_active varchar(1),
	no_def_pos numeric(38),
	no_attended numeric(38),
	no_fta numeric(38),
	no_awol numeric(38),
	pool_seq varchar(4),
	edit_tag varchar(1),
	pool_type varchar(3),
	loc_code varchar(3),
	next_date timestamp(0),
	on_call varchar(1) DEFAULT 'N',
	perm_disqual varchar(1),
	pay_county_emp varchar(1),
	pay_expenses varchar(1),
	spec_need varchar(1),
	spec_need_msg varchar(60),
	smart_card varchar(20),
	amt_spent double precision,
	completion_flag varchar(1) DEFAULT 'N',
	completion_date timestamp(0),
	sort_code varchar(6),
	bank_acct_name varchar(18),
	bank_acct_no varchar(8),
	bldg_soc_roll_no varchar(18),
	was_deferred varchar(1),
	id_checked varchar(1),
	postpone varchar(1),
	welsh varchar(1),
	paid_cash varchar(1),
	travel_time real,
	scan_code varchar(9),
	financial_loss double precision,
	police_check varchar(1),
	last_update timestamp(0),
	read_only varchar(1) DEFAULT 'N',
	summons_file varchar(20),
	reminder_sent varchar(1),
	phoenix_date timestamp(0),
	phoenix_checked varchar(1),
	m_phone varchar(15),
	h_email varchar(254),
	contact_preference smallint DEFAULT 0,
	notifications smallint DEFAULT 0,
	transfer_date timestamp(0),
	service_comp_comms_status varchar(10)
) ;


CREATE TABLE pool_comments (
	owner varchar(3) DEFAULT current_setting('juror_app.owner', true),
	pool_no varchar(9) NOT NULL,
	user_id varchar(20) NOT NULL,
	last_update timestamp(0),
	pcomment varchar(80) NOT NULL,
	no_requested numeric(38) DEFAULT 0
) ;


CREATE TABLE pool_hist (
	owner varchar(3) DEFAULT current_setting('juror_app.owner', true),
	pool_no varchar(9) NOT NULL,
	date_part timestamp(0) NOT NULL,
	history_code varchar(4) NOT NULL,
	user_id varchar(20) NOT NULL,
	other_information varchar(24),
	last_update timestamp(0)
) ;


CREATE TABLE pool_stats (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	pool_no varchar(9) NOT NULL,
	att_date timestamp(0) NOT NULL,
	no_summoned numeric(38) NOT NULL,
	no_responded numeric(38) NOT NULL,
	no_attended numeric(38) NOT NULL,
	no_excused numeric(38) NOT NULL,
	no_disqualified numeric(38) NOT NULL,
	no_deferred numeric(38) NOT NULL,
	no_reassigned numeric(38) NOT NULL,
	no_undeliverable numeric(38) NOT NULL,
	no_transferred numeric(38) NOT NULL,
	no_fta numeric(38) NOT NULL
) ;


CREATE TABLE pool_status (
	status numeric(38) NOT NULL,
	status_desc varchar(15) NOT NULL,
	active varchar(1)
) ;


CREATE TABLE pool_transfer_weekday (
	transfer_day varchar(3),
	run_day varchar(3),
	adjustment smallint
) ;


CREATE TABLE pool_type (
	pool_type varchar(3) NOT NULL,
	pool_type_desc varchar(20) NOT NULL
) ;


CREATE TABLE postpone_lett (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	date_postpone timestamp(0) NOT NULL,
	printed varchar(1),
	date_printed timestamp(0)
) ;


CREATE TABLE print_files (
	printfile_name varchar(15) NOT NULL,
	creation_date timestamp(0) NOT NULL DEFAULT statement_timestamp(),
	form_type varchar(6) NOT NULL,
	detail_rec varchar(1260) NOT NULL,
	extracted_flag varchar(1),
	part_no varchar(9) NOT NULL,
	digital_comms varchar(1) DEFAULT 'N'
) ;


CREATE TABLE race_records (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	bf_no double precision,
	bm_no double precision,
	of_no double precision,
	om_no double precision,
	wf_no double precision,
	wm_no double precision,
	record_number double precision NOT NULL
) ;


CREATE TABLE release_lett (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	date_release timestamp(0) NOT NULL,
	date_printed timestamp(0)
) ;


CREATE TABLE request_lett (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	req_info varchar(210),
	printed varchar(1),
	date_printed timestamp(0)
) ;


CREATE TABLE seating_plan (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	seating_plan numeric(38) NOT NULL,
	description varchar(30),
	seats_deep numeric(38) NOT NULL,
	seats_wide numeric(38) NOT NULL
) ;


CREATE TABLE security_level (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	login varchar(20) NOT NULL,
	menu_id numeric(38) NOT NULL,
	description varchar(80) NOT NULL,
	allow_use varchar(1) NOT NULL,
	module_code varchar(1),
	menu_heading varchar(20)
) ;


CREATE TABLE states (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	state_id varchar(2) NOT NULL,
	state_name varchar(24),
	state_capi varchar(24),
	country varchar(3)
) ;


CREATE TABLE stat_standards (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	location varchar(10) NOT NULL,
	pbi numeric(38),
	voir_dire_attend double precision,
	zero_days double precision,
	unused_juror_days numeric(38)
) ;


CREATE TABLE system_file (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	record_no numeric(38) NOT NULL,
	pool_rate1 double precision NOT NULL,
	pool_rate2 double precision NOT NULL,
	after_p1 double precision NOT NULL,
	travel_rate double precision NOT NULL,
	public_trans double precision NOT NULL,
	child_care_rate double precision NOT NULL,
	jury_rate1 double precision NOT NULL,
	jury_rate2 double precision NOT NULL,
	after_j1 double precision NOT NULL,
	pool_audit_no double precision NOT NULL,
	jury_audit_no double precision NOT NULL,
	financial_audit_no double precision NOT NULL,
	acct_pay_audit_no double precision NOT NULL,
	word_processor varchar(20),
	pay_state_empl varchar(1) NOT NULL,
	check_for_bioform varchar(1) NOT NULL,
	ins_hour_rate double precision,
	voters_count numeric(38),
	create_new_pool numeric(38),
	gather_fta varchar(1),
	exc_letter varchar(1),
	denied_letter varchar(1),
	total_source double precision,
	available_recs bigint,
	no_months_fta double precision,
	batch_no bigint,
	print_sequence varchar(4),
	print_index varchar(4),
	print_transmission varchar(2),
	print_excused varchar(4),
	allow_multi_defer varchar(1),
	start_offset bigint,
	no_days_to_process bigint,
	confirm_start_offset bigint,
	confirm_day_range bigint,
	phoenix_delay numeric(38),
	cor_max_pool_total integer
) ;


CREATE TABLE system_parameter (
	sp_id bigint NOT NULL,
	sp_desc varchar(80) NOT NULL,
	sp_value varchar(200) NOT NULL,
	created_by varchar(20),
	created_date timestamp(0),
	updated_by varchar(20),
	updated_date timestamp(0)
) ;


CREATE TABLE tempjuror (
	id varchar(9),
	surname varchar(20) NOT NULL,
	first_name varchar(20) NOT NULL,
	last_name varchar(20),
	dob timestamp(0) NOT NULL,
	postcode varchar(8) NOT NULL,
	check_complete varchar(1),
	disqualified varchar(1),
	try_count smallint
) ;


CREATE TABLE tempphoenixtemp (
	part_no varchar(9) NOT NULL,
	last_name varchar(20) NOT NULL,
	first_name varchar(20) NOT NULL,
	postcode varchar(10) NOT NULL,
	date_of_birth timestamp(0) NOT NULL,
	result varchar(1),
	checked varchar(1)
) ;


CREATE TABLE temp_missing_payment_data (
	owner varchar(3),
	loc_code varchar(3),
	total_amount bigint,
	part_no varchar(9),
	sort_code varchar(6),
	bank_acct_name varchar(18),
	bank_acct_no varchar(8),
	bldg_soc_roll_no varchar(18),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	postcode varchar(10),
	aramis_auth_code varchar(9),
	name varchar(52),
	loc_cost_centre varchar(7),
	loe_tot bigint,
	travel_tot bigint,
	subs_tot bigint,
	exp_subs_date timestamp(0)
) ;


CREATE TABLE trial (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	trial_no varchar(16) NOT NULL,
	descript varchar(30) NOT NULL,
	room_no varchar(6) NOT NULL,
	judge varchar(4) NOT NULL,
	t_type varchar(3) NOT NULL,
	no_jury double precision,
	no_alt double precision,
	voir_end_date timestamp(0),
	trial_end_date timestamp(0),
	deliberation_date timestamp(0),
	deliberation_time timestamp(0),
	sequestered_date timestamp(0),
	judgement_amount double precision,
	final_charge_code varchar(6),
	total_def_premptory double precision,
	total_pla_premptory double precision,
	trial_dte timestamp(0),
	voir_dte timestamp(0),
	date_sele timestamp(0),
	cancel_reason varchar(4),
	jurisdiction_code varchar(1),
	prosecutor_plantiff_attorney varchar(20),
	defence_attorney varchar(20),
	jury_trial varchar(1),
	jurors_requested double precision,
	jurors_sent double precision,
	sent_date timestamp(0),
	sent_time timestamp(0),
	event_disposition varchar(3),
	total_pros_plan_cause double precision,
	total_def_cause double precision,
	select_date_end timestamp(0),
	seating_plan numeric(38),
	pay_upon_complete varchar(1),
	anonymous varchar(1)
) WITH (fillfactor=70);


CREATE TABLE trial_can_reas (
	cancel_reason varchar(4) NOT NULL,
	description varchar(30) NOT NULL
) ;


CREATE TABLE trial_charge_code (
	final_charge_code varchar(6) NOT NULL,
	description varchar(30) NOT NULL
) ;


CREATE TABLE t_donation (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	donation_code varchar(4) NOT NULL,
	description varchar(40)
) ;


CREATE TABLE t_history_code (
	history_code varchar(4) NOT NULL,
	description varchar(40) NOT NULL
) ;


CREATE TABLE t_id_check (
	id_check varchar(1) NOT NULL,
	description varchar(20) NOT NULL
) ;


CREATE TABLE t_jurisdiction (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	jurisdiction_code varchar(1) NOT NULL,
	description varchar(12) NOT NULL
) ;


CREATE TABLE t_loc_juris_type (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	loc_code varchar(3) NOT NULL,
	jurisdiction_code varchar(1),
	pool_type varchar(3)
) ;


CREATE TABLE t_message_template (
	message_scope varchar(6) NOT NULL,
	message_id numeric(38) NOT NULL,
	message_title varchar(27) NOT NULL,
	message_subject varchar(100) NOT NULL,
	message_text varchar(2000),
	display_order numeric(38)
) ;


CREATE TABLE t_mileage (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	zip varchar(10) NOT NULL,
	city varchar(20) NOT NULL,
	mileage double precision
) ;


CREATE TABLE t_occupation (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	occupation_code varchar(4) NOT NULL,
	occupation_descript varchar(30)
) ;


CREATE TABLE t_phone (
	phone_code varchar(2) NOT NULL,
	description varchar(60) NOT NULL
) ;


CREATE TABLE t_police (
	police_check varchar(1) NOT NULL,
	description varchar(20)
) ;


CREATE TABLE t_race_code (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	race_code varchar(1) NOT NULL,
	race_descp varchar(30)
) ;


CREATE TABLE t_special (
	spec_need varchar(1) NOT NULL,
	description varchar(60) NOT NULL
) ;


CREATE TABLE t_type (
	t_type varchar(3) NOT NULL,
	description varchar(30) NOT NULL
) ;


CREATE TABLE undelivr (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	part_no varchar(9) NOT NULL,
	loc_code varchar(3),
	poll_number varchar(5),
	title varchar(10),
	lname varchar(20),
	fname varchar(20),
	address varchar(35),
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10)
) ;


CREATE TABLE unique_pool (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	pool_no varchar(9) NOT NULL,
	jurisdiction_code varchar(1),
	return_date timestamp(0) NOT NULL,
	next_date timestamp(0) NOT NULL,
	no_requested numeric(38) DEFAULT 0,
	pool_total numeric(38) NOT NULL DEFAULT 0,
	reg_spc varchar(1) NOT NULL,
	pool_type varchar(3),
	loc_code varchar(3),
	new_request varchar(1) DEFAULT 'Y',
	last_update timestamp(0),
	read_only varchar(1) DEFAULT 'N',
	deferrals_used bigint,
	additional_summons bigint,
	attend_time timestamp(0)
) ;


CREATE TABLE user_level_menus (
	owner varchar(3) NOT NULL DEFAULT current_setting('juror_app.owner', true),
	menu_id integer NOT NULL,
	module_code varchar(1),
	menu_heading varchar(20),
	description varchar(100),
	allow_use varchar(1),
	level1 varchar(1),
	level2 varchar(1),
	level3 varchar(1),
	level4 varchar(1),
	level5 varchar(1),
	level9 varchar(1) DEFAULT 'N'
) ;


CREATE TABLE venire (
	owner varchar(3) DEFAULT current_setting('juror_app.owner', true),
	login varchar(20) NOT NULL,
	part_no varchar(9) NOT NULL,
	lname varchar(20),
	fname varchar(20),
	address varchar(40),
	city varchar(20),
	state varchar(2),
	zip varchar(10),
	loc_code varchar(3),
	jurisdiction_code varchar(1),
	voter_reg varchar(11),
	ret_date timestamp(0)
) ;


CREATE TABLE voters127 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters401 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters402 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters403 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters404 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters406 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters407 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters408 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters409 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters410 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters411 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters412 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters413 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters414 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters415 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters416 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters417 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters418 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters419 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters420 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters421 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters422 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters423 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters424 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters425 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters426 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters427 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters428 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters429 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters430 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters431 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters432 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters433 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters434 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters435 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters436 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters437 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters439 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters440 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters441 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters442 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters443 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters444 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters445 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters446 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters447 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters448 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters449 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters450 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters451 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters452 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters453 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters454 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters455 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters456 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters457 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters458 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters459 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters460 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters461 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters462 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters463 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters464 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters465 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters466 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters467 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters468 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters469 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters470 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters471 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters472 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters473 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters474 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters475 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters476 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters477 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters478 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters479 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters480 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters626 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters750 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters751 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters754 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters755 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters756 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters758 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters761 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters762 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters765 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters767 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters768 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters769 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters772 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters774 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters794 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters795 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters796 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters797 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters798 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE voters799 (
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


CREATE TABLE welsh_location (
	owner varchar(3) DEFAULT current_setting('juror_app.owner', true),
	loc_code varchar(3) NOT NULL,
	loc_name varchar(40) NOT NULL,
	loc_address1 varchar(35) NOT NULL,
	loc_address2 varchar(35),
	loc_address3 varchar(35),
	loc_address4 varchar(35),
	loc_address5 varchar(35),
	loc_address6 varchar(35),
	last_update timestamp(0),
	location_address varchar(230)
) ;
