-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW cert_letter (owner, part_no, printed, date_printed) AS SELECT
    cl.OWNER,
    cl.PART_NO,
    cl.PRINTED,
    cl.DATE_PRINTED
  FROM JUROR.CERT_LETT cl;

