-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW coroner_pool_detail (cor_pool_no, part_no, title, fname, lname, address1, address2, address3, address4, address5, address6, postcode) AS SELECT
    c.COR_POOL_NO,
    c.PART_NO,
    c.TITLE,
    c.FNAME,
    c.LNAME,
    c.ADDRESS1,
    c.ADDRESS2,
    c.ADDRESS3,
    c.ADDRESS4,
    c.ADDRESS5,
    c.ADDRESS6,
    c.POSTCODE
  FROM
    JUROR.CORONER_POOL_DETAIL c;

