-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW exc_code (exc_code, description) AS SELECT
    e.EXC_CODE,
    e.DESCRIPTION
  FROM JUROR.EXC_CODE e
  WHERE ENABLED='Y';

