-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW juror_responses_summoned (part_no, pool_no, status, is_active, read_only, processing_status, processing_complete, completed_at, welsh) AS SELECT
      P.PART_NO,
      P.POOL_NO,
      P.STATUS,
      P.IS_ACTIVE,
      P.READ_ONLY,
      R.PROCESSING_STATUS,
      R.PROCESSING_COMPLETE,
      R.COMPLETED_AT ,
      R.WELSH
    FROM
      JUROR_DIGITAL.JUROR_RESPONSE R,
      JUROR.POOL P
    WHERE
       P.OWNER = '400'
      AND P.IS_ACTIVE = 'Y'
      AND (P.status <> 1 OR (P.status = 1 AND P.read_only = 'Y'))
      AND R.PROCESSING_STATUS = 'TODO'
      AND R.JUROR_NUMBER = P.PART_NO;

