-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW messages (part_no, file_datetime, username, loc_code, phone, email, loc_name, pool_no, subject, message_text, message_id, message_read) AS SELECT 
   M.PART_NO,
   M.FILE_DATETIME,
   M.USERNAME,
   M.LOC_CODE,
   M.PHONE,
   M.EMAIL,
   M.LOC_NAME,
   M.POOL_NO,
   M.SUBJECT,
   M.MESSAGE_TEXT,
   M.MESSAGE_ID,
   M.MESSAGE_READ
  FROM JUROR.MESSAGES M;

