-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW part_amendments (owner, part_no, edit_date, edit_userid, title, fname, lname, dob, address, zip, sort_code, bank_acct_name, bank_acct_no, bldg_soc_roll_no, pool_no) AS SELECT
    pa.OWNER,
    pa.PART_NO,
    pa.EDIT_DATE,
    pa.EDIT_USERID,
    pa.TITLE,
    pa.FNAME,
    pa.LNAME,
    pa.DOB,
    pa.ADDRESS,
    pa.ZIP,
    pa.SORT_CODE,
    pa.BANK_ACCT_NAME,
    pa.BANK_ACCT_NO,
    pa.BLDG_SOC_ROLL_NO,
    pa.POOL_NO
  FROM
    JUROR.PART_AMENDMENTS pa;

