-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW phone_log (owner, part_no, phone_code, user_id, notes, last_update, start_call, end_call) AS SELECT
    OWNER,
    PART_NO,
    PHONE_CODE,
    USER_ID,
    NOTES,
    LAST_UPDATE,
    START_CALL,
    END_CALL
  FROM JUROR.PHONE_LOG
  WHERE OWNER = '400';

