-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW stats_not_responded_totals (not_responsed_total) AS SELECT  
   sum(nvl(S.non_responsed_count,0))
   FROM
    JUROR_DIGITAL.stats_not_responded S;

