-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.3;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital_user,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW unique_pool (additional_summons, attend_time, last_update, loc_code, new_request, next_date, pool_no, return_date) AS SELECT
  u.ADDITIONAL_SUMMONS,
  u.ATTEND_TIME,
  u.LAST_UPDATE,
  u.LOC_CODE,
  u.NEW_REQUEST,
  u.NEXT_DATE,
  u.POOL_NO,
  u.RETURN_DATE
FROM JUROR.UNIQUE_POOL u
  WHERE
    u.owner = '400';

