-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = JUROR,public;
\set ON_ERROR_STOP ON





CREATE OR REPLACE PROCEDURE JUROR.INSERT_VOTERS () AS $body$
DECLARE


   c_voters_table CURSOR FOR
             SELECT table_name from user_tables where table_name like 'VOTERS%'
             order by TABLE_NAME asc;

   sql_insert varchar(1000);
BEGIN

 FOR voters_table IN c_voters_table
    loop

        sql_insert := 'INSERT INTO JUROR_DIGITAL.VOTERS SELECT ''' || SUBSTR( voters_table.table_name, 7, 3) || ''' AS LOC_CODE, PART_NO, REGISTER_LETT, POLL_NUMBER, NEW_MARKER, TITLE, LNAME, FNAME, DOB, FLAGS, ADDRESS, ADDRESS2, ADDRESS3, ADDRESS4, ADDRESS5, ADDRESS6, ZIP, DATE_SELECTED1, DATE_SELECTED2, DATE_SELECTED3, REC_NUM, PERM_DISQUAL, SOURCE_ID FROM JUROR.' || voters_table.table_name;
        RAISE NOTICE '%', sql_insert;
		EXECUTE sql_insert;

   END loop;

EXCEPTION
   WHEN OTHERS THEN
      RAISE NOTICE '%',  SQLERRM;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON PROCEDURE JUROR.INSERT_VOTERS () FROM PUBLIC;

