-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.2;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = hk,public;



   -----------
   --
   -----------
   


CREATE OR REPLACE PROCEDURE hk.housekeeping_nocommit_parent_delete_trial () AS $body$
DECLARE

   
     ora2pg_rowcount int;
l_start timestamp(0);

   
BEGIN
   
     PERFORM set_config('housekeeping_nocommit.l_error_stage', 'ACCUSED', false);

     utl_file.put_line(l_file,' ',TRUE);
     utl_file.put_line(l_file,'Row Counts for POOL PARENT tables',TRUE);
     utl_file.put_line(l_file,'Table,Deleted,Start Time,End Time',TRUE);
  
      l_start := clock_timestamp();

     DELETE FROM accused ac
     WHERE  EXISTS (SELECT null 
                    FROM   trial tr
                    WHERE  trial_end_date + current_setting('housekeeping_nocommit.l_param_court_threshold')::integer < clock_timestamp()
                    AND    tr.owner = ac.owner
                    AND    tr.trial_no = ac.trial_no
                    AND NOT EXISTS (SELECT null
                                    FROM   panel pl
                                    WHERE  tr.trial_no = pl.trial_no 
                                    AND    tr.owner = pl.owner
                                    )
                    );

     GET DIAGNOSTICS ora2pg_rowcount = ROW_COUNT;


     utl_file.put_line(l_file,'ACCUSED,'|| ora2pg_rowcount||','||TO_CHAR(l_start,'DD-MM-YYYY hh24:MI:SS')||','||TO_CHAR(clock_timestamp(),'DD-MM-YYYY hh24:MI:SS') ,TRUE);

       
     PERFORM set_config('housekeeping_nocommit.l_error_stage', 'TRIAL', false);
     l_start := clock_timestamp();

     DELETE FROM trial ab
     WHERE  trial_end_date + current_setting('housekeeping_nocommit.l_param_court_threshold')::integer < clock_timestamp()
     AND NOT EXISTS (SELECT null
                     FROM   panel pl
                     WHERE  ab.trial_no = pl.trial_no 
                     AND    ab.owner = pl.owner
                     );

     GET DIAGNOSTICS ora2pg_rowcount = ROW_COUNT;


     utl_file.put_line(l_file,'TRIAL,'|| ora2pg_rowcount||','||TO_CHAR(l_start,'DD-MM-YYYY hh24:MI:SS')||','||TO_CHAR(clock_timestamp(),'DD-MM-YYYY hh24:MI:SS') ,TRUE);

      IF p_read_only_mode THEN
        ROLLBACK;
      ELSE
        NULL;
        -- COMMIT;  **testing
      END IF;


   EXCEPTION
     WHEN others THEN
     
       ROLLBACK;

       PERFORM set_config('housekeeping_nocommit.l_err_msg', SUBSTR(sqlerrm,1,200), false);
       RAISE EXCEPTION 'e_delete_error' USING ERRCODE = '50001';
 
   END;

$body$
LANGUAGE PLPGSQL
;
-- REVOKE ALL ON PROCEDURE hk.housekeeping_nocommit_parent_delete_trial () FROM PUBLIC;
