-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = JUROR,public;


/************************************************************************
 *	FUNCTION:	phoenixinterface_jurorFirstName( name_in VARCHAR2 )
 *	Access  :	private
 *	Args In :	name_in (juror first name)
 *	Returns :	s_name (Varchar2)
 *
 *	Desc    :	This function analyses the jurors first name and returns a single first name
 *            having determined if it contains components names such as to such as initials
 *            titles and middlenames etc.
 *
 *            This function will :
 *            1) Remove unwanted chars from the middle name (see Jurorcleanname)
 *            2) Remove ALL BUT the first name if other component names are present
 *            Example: Daniel [SNR] Jake Lewis --> Daniel
 *                     [SNR] William P.        --> William
 *
 *  History
 *
 *	Version Name		  Date		 Desc
 *	======= ========= ======== ====
 *  V1.0    ???       ???      Initial version
 *	V1.2    Kal Sohal 20/11/06 SCR 4341 PNC Errors.
 *  V1.3    M Turton  21/03/11 Trac3897 Handle characters in () and []
 ************************************************************************/
CREATE OR REPLACE FUNCTION phoenixinterface_jurorFirstName ( name_in text ) RETURNS varchar AS $body$
DECLARE


      n_pos            bigint;
      s_name           varchar(20);


BEGIN

      -- Replace all full stops and commas with a space and
      -- Remove anything within brackets () or [] and
      -- Remove leading and trailing spaces...
      s_name := phoenixinterface_jurorCleanName(name_in);

      -- If there is a 'split' in the name, keep Firstname
      n_pos  := position(' '  in s_name);

      IF n_pos  > 0 THEN
         s_name := Substr(s_name, 1, n_pos-1);
      END IF;

      -- Check for NULL and return firstname in uppercase
      s_name := coalesce(s_name, '~');  --Trac3897 If null supply tilde
      --Return UPPER(Trim(s_name));
      Return UPPER(s_name);

   EXCEPTION
      WHEN OTHERS THEN
         CALL phoenixinterface_write_error( 'Error in jurorFirstName ' );

   END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION phoenixinterface_jurorFirstName ( name_in text ) FROM PUBLIC;
