-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';
SET search_path = JUROR,public;


/*****************************************************************************

 *  History
 *
 *	Version Name	   Date		Desc
 *	======= =========  ====		=====
 *	V1.0    x			Initial version
 *	V2.0    M Turton   15/03/11	Trac3897 Clean surname as per first and middle name
 ************************************************************************/
CREATE OR REPLACE FUNCTION phoenixinterface_jurorSurname ( name_in text ) RETURNS varchar AS $body$
DECLARE


      space_pos            bigint;
      s_name               varchar(20);
      sur_name             varchar(20);
      temp_name            varchar(20);



BEGIN
      -- Replace all full stops and commas with a space and
      -- Remove anything within brackets () or [] and
      -- Remove leading and trailing spaces...
      s_name := phoenixinterface_jurorCleanName(name_in);

      s_name := coalesce(s_name, '~');  --Trac3897 If null supply tilde
      --s_name = Trim(s_name); --Trac3897 - remove spaces before and after
      --temp_name := REPLACE( name_in, '`', '''' ); //Trac3697
      temp_name := REPLACE( s_name, '`', '''' );

      sur_name := REPLACE( temp_name, ',', '''' );

      temp_name := replace(sur_name, ' ' , '');

      return UPPER(replace(temp_name, '.' , '') );

   EXCEPTION
      WHEN OTHERS THEN
         CALL phoenixinterface_write_error( 'Error in jurorSurname ');

   END;

$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION phoenixinterface_jurorSurname ( name_in text ) FROM PUBLIC;
