-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.4;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW abaccus (form_type, creation_date, number_of_items) AS SELECT			pf.FORM_TYPE
				,to_date(pf.CREATION_DATE::TEXT, 'YYYY-MM-DD') AS CREATION_DATE
				,COUNT(pf.PART_NO) AS NUMBER_OF_ITEMS
FROM			JUROR.PRINT_FILES pf
GROUP BY		pf.FORM_TYPE
				,TO_DATE(pf.CREATION_DATE);

