-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.4;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital,public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE VIEW loc_postcode_totals_view (loc_code, zip, total, total_cor) AS SELECT
    LOC_CODE,
    ZIP,
    SUM(CASE WHEN DATE_SELECTED1 IS NULL
        AND PERM_DISQUAL IS NULL THEN 1 ELSE 0 END) AS TOTAL,
    SUM(CASE WHEN DATE_SELECTED1 IS NULL
        AND PERM_DISQUAL IS NULL
        AND FLAGS IS NULL THEN 1 ELSE 0 END) AS TOTAL_COR
    FROM
    JUROR_DIGITAL.VOTERS
GROUP BY
    LOC_CODE ,
    ZIP;

