-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = JUROR,public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS PART_HIST_UPDATE ON PART_HIST CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_part_hist_update() RETURNS trigger AS $BODY$
BEGIN
            NEW.LAST_UPDATE := statement_timestamp();
RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_part_hist_update() FROM PUBLIC;

CREATE TRIGGER PART_HIST_UPDATE
       BEFORE INSERT OR UPDATE
       ON PART_HIST
       FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_part_hist_update();

