-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = "JUROR",public;
\set ON_ERROR_STOP ON

FUNCTION Get_Pool_Comments (pd_StartDate DATE, pd_EndDate DATE, pc_LocCode VARCHAR2)
RETURN VARCHAR2 IS

/******************************************************************************
   NAME:       GET_POOL_COMMENTS
   PURPOSE:    To concatenate the comments for a given location

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        28-05-2003   Jeeva Konar       1. Created this function.

   PARAMETERS:
   INPUT	  		:	  pd_StartDate Date, pd_EndDate Date, pc_LocCode Varchar2
   OUTPUT:
   RETURNED VALUE	:	  Varchar2
   CALLED BY		:	  yield_performance_report in PowerBuilder application


      ******************************************************************************/
CURSOR c1(cd_StartDate DATE, cd_EndDate DATE, cc_PoolNo VARCHAR2)
  IS
     SELECT pool_no, pcomment
  	 FROM   pool_comments
  	 WHERE  pool_no IN (
  		 		 	  SELECT pool_no
					  FROM   UNIQUE_POOL
					  WHERE  return_date BETWEEN cd_StartDate AND cd_EndDate
					  AND    pool_no LIKE cc_PoolNo)
     ORDER BY pool_no, last_update ;

  lc_Comments VARCHAR2(2000);
  lc_TempComments VARCHAR2(100);


 FUNCTION word_wrap( p_string IN VARCHAR2, p_len IN NUMBER DEFAULT 35 )
  RETURN VARCHAR2  AS
  l_string    LONG DEFAULT REPLACE( p_string || CHR(10), CHR(9), '    ' );
  l_result    LONG DEFAULT NULL;
  l_piece     LONG;
  l_ws        VARCHAR2(25) DEFAULT ' ' || CHR(9);
  l_sep       VARCHAR2(5) DEFAULT NULL;
  n           NUMBER;
 BEGIN
      LOOP
          EXIT WHEN l_string IS NULL;
          n := INSTR( l_string, CHR(10) );
          l_piece := SUBSTR( l_string, 1, n-1 );
       l_string := SUBSTR( l_string, n+1 );
         LOOP
            EXIT WHEN l_piece IS NULL;
              n := LENGTH(l_piece);
           IF ( n > p_len ) THEN
               n := INSTR( SUBSTR(TRANSLATE(l_piece,l_ws,RPAD(' ',LENGTH(l_ws))), 1, p_len ), ' ', -1);
                 IF ( NVL(n,0) = 0 ) THEN
                  n := p_len;
                 END IF;
              END IF;
            l_result := l_result || l_sep || SUBSTR( l_piece, 1, n );
             l_sep := CHR(10);
             l_piece := SUBSTR( l_piece, n+1 );
         END LOOP;
      END LOOP;
      RETURN l_result;
  END;

  BEGIN

    FOR i IN c1(pd_StartDate, pd_EndDate, pc_LocCode||'%') LOOP
	 	lc_TempComments := word_wrap(i.pool_no||' : '||i.pcomment,28);
	    lc_Comments := lc_Comments||lc_TempComments||CHR(13);
	END LOOP;

	RETURN NVL(lc_Comments,'');

 EXCEPTION
   WHEN OTHERS THEN
     RETURN ''	;

 END Get_Pool_Comments;

