-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = "JUROR",public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE package phoenix_checking as

  function finalise return integer;

end phoenix_checking;





CREATE OR REPLACE package body phoenix_checking as

PROCEDURE	write_error(p_info varchar2);
lc_Job_Type	error_log.JOB%type;

function finalise return integer is

  cursor police_check is
  select t.part_no,
         t.last_name,
         t.first_name,
         t.postcode,
         t.date_of_birth,
         t.result,
         t.checked,
	 p.pool_no,
	 p.read_only,
	 p.loc_code,
	 p.rowid row_idd
  from   phoenix_temp t, pool p
  where  (t.result='P' or t.result='F')
  and	 p.owner = '400'
  and	 p.part_no = t.part_no
  and 	 p.is_active = 'Y';

  l_owner    varchar2(3);

begin

lc_Job_Type := 'PHOENIX_CHECKING.FINALISE';

  for each_participant in police_check loop

    update pool
    set    phoenix_checked = decode(each_participant.checked,'C','C','U','U',NULL,'U'),
	  		 police_check	 = decode(each_participant.result, 'P','P','F','F'),
			 status			 = decode(each_participant.result, 'P',status,'F','6'),
			 disq_code		 = decode(each_participant.result, 'F','E',NULL),
			 date_disq		 = decode(each_participant.result, 'F',sysdate,NULL)
    where  rowid = each_participant.row_idd;

    if each_participant.result = 'P' then
        -- RFS 3681 Changed value for other_information
        insert into part_hist (owner,
			     part_no,
                             date_part,
                             history_code,
                             user_id,
                             other_information,
                             pool_no)
                     values ( '400',
			     each_participant.part_no,
                             sysdate,
                             'POLG',
                             'SYSTEM',
                             decode(each_participant.checked,'C','Passed','U','Unchecked - timed out',NULL,'Unchecked - timed out'),
                             each_participant.pool_no);
      else
        insert into disq_lett (owner,
			       part_no,
                               disq_code,
                               date_disq,
                               date_printed,
                               printed)
                       values ('400',
			       each_participant.part_no,
                               'E',
                               sysdate,
                               null,
                               null);

        -- RFS 3681 Changed value for other_information
        insert into part_hist (owner,
			       part_no,
                               date_part,
                               history_code,
                               user_id,
                               other_information,
                               pool_no)
                        values ( '400',
			       			   each_participant.part_no,
                               sysdate,
                               'POLF',
                               'SYSTEM',
                               'Failed',
                               each_participant.pool_no);

        insert into part_hist (owner,
			       			  part_no,
                               date_part,
                               history_code,
                               user_id,
                               other_information,
                               pool_no)
                        values ( '400',
			       			   each_participant.part_no,
                               sysdate+(1/86400),
                               'PDIS',
                               'SYSTEM',
                               'Disqualify - E',
                               each_participant.pool_no);

     end if;



    -- RFS 3681 Update/insert court copy of juror record if juror has already transfered to the court

    if each_participant.read_only = 'Y' then

       select context_id
       into l_owner
       from context_data
       where loc_code = each_participant.loc_code;

       update pool
       set    phoenix_checked = decode(each_participant.checked,'C','C','U','U',NULL,'U'),
	  		 police_check	 = decode(each_participant.result, 'P','P','F','F'),
			 status			 = decode(each_participant.result, 'P',status,'F','6'),
			 disq_code		 = decode(each_participant.result, 'F','E',NULL),
			 date_disq		 = decode(each_participant.result, 'F',sysdate,NULL)
       where owner = l_owner and part_no = each_participant.part_no and is_active = 'Y';

       if each_participant.result = 'P' then
          insert into part_hist (owner,
			     part_no,
                             date_part,
                             history_code,
                             user_id,
                             other_information,
                             pool_no)
                     values ( l_owner,
			     each_participant.part_no,
                             sysdate,
                             'POLG',
                             'SYSTEM',
                             decode(each_participant.checked,'C','Passed','U','Unchecked - timed out',NULL,'Unchecked - timed out'),
                             each_participant.pool_no);
        else
          insert into part_hist (owner,
			       part_no,
                               date_part,
                               history_code,
                               user_id,
                               other_information,
                               pool_no)
                        values ( l_owner ,
			       each_participant.part_no,
                               sysdate,
                               'POLF',
                               'SYSTEM',
                               'Failed',
                               each_participant.pool_no);

          insert into part_hist (owner,
			       part_no,
                               date_part,
                               history_code,
                               user_id,
                               other_information,
                               pool_no)
                        values ( l_owner,
			       each_participant.part_no,
                               sysdate+(1/86400),
                               'PDIS',
                               'SYSTEM',
                               'Disqualify - E',
                               each_participant.pool_no);
       end if;

     end if;

   end loop;

   delete from phoenix_temp where result = 'P' or result = 'F';

   return(0);

exception
     when others then
	write_error(sqlerrm);
	raise;
       return(1);

end finalise;

PROCEDURE write_error(p_info varchar2) IS
 pragma autonomous_transaction;

 BEGIN
     INSERT INTO ERROR_LOG (job, error_info) values (lc_Job_Type, p_info);
	 commit;
 END write_error;

end phoenix_checking;


