-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=172.17.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = "JUROR",public;
\set ON_ERROR_STOP ON

CREATE OR REPLACE PACKAGE pkg_crypto
IS


    FUNCTION get_hash(pin_string IN  VARCHAR2, pin_lenreqd in Number) RETURN VARCHAR2 ;

    FUNCTION get_hash(pin_string IN  VARCHAR2) RETURN VARCHAR2 ;


END pkg_crypto;


CREATE OR REPLACE PACKAGE BODY pkg_crypto AS

-----------------------------------------------------------------------------------
--  Function: get_hash(pin_string IN  VARCHAR2, pin_lenreqd in Number)
--
--  Parms in: pin_string - string for which hash value is required
--            pin_lenreqd- Length of HASH vaklue reqd for above
--
--  Returns:  HASH value of specified fixed length
--
--  Description
--  ===========
--  Returns fixed length HASH value for specified string.
--
--  History
--
--	Version Name		  Date		 Desc
--	======= ========= ======== ====
--	V1.0    Kal Sohal 05/06/07 Initial version
-----------------------------------------------------------------------------------
    FUNCTION get_hash(pin_string IN  VARCHAR2, pin_lenreqd in Number) RETURN VARCHAR2 IS


    l_hash RAW(64);

    BEGIN
      l_hash := dbms_crypto.hash (UTL_I18N.STRING_TO_RAW(pin_string, 'AL32UTF8'), dbms_crypto.hash_sh1);
      Return Substr(l_hash, 0, pin_lenreqd);

    EXCEPTION
      WHEN OTHERS THEN
           Raise_application_error (-2000, 'pck_crypto.get_hash()  SQLcode = ' || SQLCODE || ' SQLErrm = ' || SQLERRM);
           RETURN NULL;
    END get_hash;



-----------------------------------------------------------------------------------
--  Function: get_hash(pin_string)
--
--  Parms in: pin_string - string for which hash value is required
--
--  Returns:  HASH value of fixed length
--
--  Description
--  ===========
--  Returns fixed length HASH value for specified string.
--
--  History
--
--	Version Name		  Date		 Desc
--	======= ========= ======== ====
--	V1.0    Kal Sohal 05/06/07 Initial version
-----------------------------------------------------------------------------------
    FUNCTION get_hash(pin_string IN  VARCHAR2) RETURN VARCHAR2 IS

    BEGIN
      Return get_hash(pin_string, 200);
    EXCEPTION
      WHEN OTHERS THEN
           Raise_application_error (-2000, 'pck_crypto.get_hash()  SQLcode = ' || SQLCODE || ' SQLErrm = ' || SQLERRM);
           RETURN NULL;
    END get_hash;

END pkg_crypto;