-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.0.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';

SET search_path = juror_digital,public;
\set ON_ERROR_STOP ON

\i './schema/views/ABACCUS_view.sql'
\i './schema/views/SUMMONS_SNAPSHOT_view.sql'
\i './schema/views/LOC_POSTCODE_TOTALS_VIEW_view.sql'
\i './schema/views/MOJ_JUROR_DETAIL_view.sql'