-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.0
-- Copyright 2000-2023 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=10.0.0.5;sid=xe;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE SCHEMA IF NOT EXISTS juror_digital;
ALTER SCHEMA juror_digital OWNER TO juror_digital;

SET search_path = juror_digital,public;


CREATE TABLE app_settings (
	setting varchar(80) NOT NULL,
	value varchar(200)
) ;


CREATE TABLE bureau_auth (
	username varchar(20) NOT NULL,
	loginattempts bigint NOT NULL
) ;


CREATE TABLE change_log (
	id bigint NOT NULL,
	juror_number varchar(9),
	timestamp timestamp,
	staff varchar(20),
	type varchar(50),
	notes varchar(2000),
	version bigint
) ;


CREATE TABLE change_log_item (
	id bigint NOT NULL,
	change_log bigint,
	old_key varchar(128),
	old_value varchar(2048),
	new_key varchar(128),
	new_value varchar(2048),
	version bigint
) ;


CREATE TABLE contact_log_ext (
	part_no varchar(9) NOT NULL,
	start_call timestamp(0) NOT NULL,
	repeat_enquiry varchar(1) NOT NULL
) ;


CREATE TABLE coroner_pool_ext (
	cor_pool_no varchar(9) NOT NULL,
	email varchar(254) NOT NULL,
	phone varchar(15)
) ;


CREATE TABLE court_region (
	region_id varchar(5) NOT NULL,
	region_name varchar(30) NOT NULL,
	notify_account_key varchar(100)
) ;


CREATE TABLE court_whitelist (
	loc_code varchar(3) NOT NULL
) ;


CREATE TABLE expenses_rates (
	expense_type varchar(80) NOT NULL,
	rate real
) ;


CREATE TABLE jd_housekeeping_audit (
	juror_number varchar(9),
	selected_date timestamp(0),
	deletion_date timestamp(0),
	deletion_summary varchar(1500)
) ;


CREATE TABLE juror_response (
	juror_number varchar(9) NOT NULL,
	date_received timestamp(0) NOT NULL,
	title varchar(10),
	first_name varchar(20),
	last_name varchar(20),
	address varchar(35),
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	processing_status varchar(50),
	date_of_birth timestamp(0),
	phone_number varchar(15),
	alt_phone_number varchar(15),
	email varchar(254),
	residency varchar(1) NOT NULL DEFAULT 'N',
	residency_detail varchar(1000),
	mental_health_act varchar(1) NOT NULL DEFAULT 'N',
	mental_health_act_details varchar(2020),
	bail varchar(1) NOT NULL DEFAULT 'N',
	bail_details varchar(1000),
	convictions varchar(1) NOT NULL DEFAULT 'N',
	convictions_details varchar(1000),
	deferral_reason varchar(1000),
	deferral_date varchar(1000),
	special_needs_arrangements varchar(1000),
	excusal_reason varchar(1000),
	processing_complete varchar(1) DEFAULT 'N',
	version bigint DEFAULT 0,
	thirdparty_fname varchar(50),
	thirdparty_lname varchar(50),
	relationship varchar(50),
	main_phone varchar(50),
	other_phone varchar(50),
	email_address varchar(254),
	thirdparty_reason varchar(1000),
	thirdparty_other_reason varchar(1000),
	juror_phone_details varchar(1),
	juror_email_details varchar(1),
	staff_login varchar(20),
	staff_assignment_date timestamp(0),
	urgent varchar(1) DEFAULT 'N',
	super_urgent varchar(1) DEFAULT 'N',
	completed_at timestamp,
	welsh varchar(1) DEFAULT 'N'
) ;


CREATE TABLE juror_response_aud (
	juror_number varchar(9),
	changed timestamp(0),
	login varchar(20),
	old_processing_status varchar(50),
	new_processing_status varchar(50)
) ;


CREATE TABLE juror_response_cjs_employment (
	juror_number varchar(9) NOT NULL,
	cjs_employer varchar(100) NOT NULL,
	cjs_employer_details varchar(1000) NOT NULL,
	id bigint NOT NULL
) ;


CREATE TABLE juror_response_special_needs (
	juror_number varchar(9) NOT NULL,
	spec_need varchar(1) NOT NULL,
	spec_need_detail varchar(1000) NOT NULL,
	id bigint NOT NULL
) ;


CREATE TABLE notify_template_field (
	id integer NOT NULL,
	template_id varchar(50) NOT NULL,
	template_field varchar(40) NOT NULL,
	database_field varchar(80) NOT NULL,
	position_from smallint,
	position_to smallint,
	field_length smallint,
	convert_to_date varchar(1) DEFAULT 'N',
	jd_class_name varchar(60),
	jd_class_property varchar(60),
	version bigint
) ;


CREATE TABLE notify_template_mapping (
	template_id varchar(50) NOT NULL,
	template_name varchar(40) NOT NULL,
	notify_name varchar(60) NOT NULL,
	form_type varchar(6),
	notification_type smallint,
	version bigint
) ;


CREATE TABLE paper_response (
	juror_number varchar(9) NOT NULL,
	date_received timestamp(0) NOT NULL,
	title varchar(10),
	first_name varchar(20),
	last_name varchar(20),
	address varchar(35),
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	zip varchar(10),
	processing_status varchar(50),
	date_of_birth timestamp(0),
	phone_number varchar(15),
	alt_phone_number varchar(15),
	email varchar(254),
	residency varchar(1),
	mental_health_act varchar(1),
	mental_health_capacity varchar(1),
	bail varchar(1),
	convictions varchar(1),
	special_needs_arrangements varchar(1000),
	relationship varchar(50),
	thirdparty_reason varchar(1000),
	deferral varchar(1) DEFAULT 'N',
	excusal varchar(1) DEFAULT 'N',
	signed varchar(1),
	staff_login varchar(20),
	urgent varchar(1) DEFAULT 'N',
	super_urgent varchar(1) DEFAULT 'N',
	processing_complete varchar(1) DEFAULT 'N',
	completed_at timestamp,
	welsh varchar(1) DEFAULT 'N'
) ;


CREATE TABLE paper_response_cjs_employment (
	juror_number varchar(9) NOT NULL,
	cjs_employer varchar(100) NOT NULL,
	cjs_employer_details varchar(1000),
	id bigint NOT NULL
) ;


CREATE TABLE paper_response_special_needs (
	juror_number varchar(9) NOT NULL,
	spec_need varchar(1) NOT NULL,
	spec_need_detail varchar(1000),
	id bigint NOT NULL
) ;


CREATE TABLE pool_extend (
	part_no varchar(9) NOT NULL,
	is_locked varchar(1) DEFAULT 'N'
) ;


CREATE TABLE pool_member_ext (
	owner varchar(3) NOT NULL,
	part_no varchar(9) NOT NULL,
	pool_no varchar(9) NOT NULL,
	optic_reference varchar(8)
) ;


CREATE TABLE pool_request_ext (
	pool_no varchar(9) NOT NULL,
	total_no_required numeric(38) NOT NULL,
	last_update timestamp(0)
) ;


CREATE TABLE region_notify_template (
	region_template_id smallint NOT NULL,
	template_name varchar(100),
	region_id varchar(5),
	triggered_template_id varchar(100),
	legacy_template_id bigint,
	notify_template_id varchar(100),
	message_format varchar(10),
	welsh_language varchar(1)
) ;


CREATE TABLE staff (
	login varchar(20) NOT NULL,
	name varchar(50),
	rank bigint,
	active bigint,
	court_1 varchar(3),
	court_2 varchar(3),
	court_3 varchar(3),
	court_4 varchar(3),
	court_5 varchar(3),
	court_6 varchar(3),
	court_7 varchar(3),
	court_8 varchar(3),
	court_9 varchar(3),
	court_10 varchar(3),
	version bigint,
	team_id bigint
) ;


CREATE TABLE staff_audit (
	action varchar(20) NOT NULL,
	editor_login varchar(20) NOT NULL,
	created timestamp NOT NULL,
	login varchar(20),
	name varchar(50),
	rank bigint,
	active bigint,
	court_1 varchar(3),
	court_2 varchar(3),
	court_3 varchar(3),
	court_4 varchar(3),
	court_5 varchar(3),
	court_6 varchar(3),
	court_7 varchar(3),
	court_8 varchar(3),
	court_9 varchar(3),
	court_10 varchar(3),
	team_id bigint,
	version bigint
) ;


CREATE TABLE staff_juror_response_audit (
	team_leader_login varchar(20) NOT NULL,
	staff_login varchar(20),
	juror_number varchar(9) NOT NULL,
	date_received timestamp NOT NULL,
	staff_assignment_date timestamp(0) NOT NULL,
	created timestamp NOT NULL,
	version bigint
) ;


CREATE TABLE stats_auto_processed (
	processed_date timestamp(0) NOT NULL,
	processed_count integer DEFAULT 0
) ;


CREATE TABLE stats_deferrals (
	bureau_or_court varchar(6) NOT NULL,
	exec_code varchar(1) NOT NULL,
	calendar_year varchar(4) NOT NULL,
	financial_year varchar(7) NOT NULL,
	week varchar(7) NOT NULL,
	excusal_count integer NOT NULL
) ;


CREATE TABLE stats_excusals (
	bureau_or_court varchar(6) NOT NULL,
	exec_code varchar(1) NOT NULL,
	calendar_year varchar(4) NOT NULL,
	financial_year varchar(7) NOT NULL,
	week varchar(7) NOT NULL,
	excusal_count integer NOT NULL
) ;


CREATE TABLE stats_not_responded (
	summons_month timestamp(0) NOT NULL,
	loc_code varchar(3) NOT NULL,
	non_responsed_count integer DEFAULT 0
) ;


CREATE TABLE stats_response_times (
	summons_month timestamp(0) NOT NULL,
	response_month timestamp(0) NOT NULL,
	response_period varchar(15) NOT NULL,
	loc_code varchar(3) NOT NULL,
	response_method varchar(13) NOT NULL,
	response_count integer DEFAULT 0
) ;


CREATE TABLE stats_thirdparty_online (
	summons_month timestamp(0) NOT NULL,
	thirdparty_response_count integer DEFAULT 0
) ;


CREATE TABLE stats_unprocessed_responses (
	loc_code varchar(3) NOT NULL,
	unprocessed_count integer DEFAULT 0
) ;


CREATE TABLE stats_welsh_online_responses (
	summons_month timestamp(0) NOT NULL,
	welsh_response_count integer DEFAULT 0
) ;


CREATE TABLE survey_response (
	id varchar(20) NOT NULL,
	survey_id varchar(20) NOT NULL,
	user_no numeric(38),
	survey_response_date timestamp(0),
	satisfaction_desc varchar(50),
	created timestamp DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC'))
) ;


CREATE TABLE team (
	id bigint NOT NULL,
	team_name varchar(1000) NOT NULL,
	version bigint
) ;


CREATE TABLE voters (
	loc_code varchar(3) NOT NULL,
	part_no varchar(9) NOT NULL,
	register_lett varchar(5),
	poll_number varchar(5),
	new_marker varchar(1),
	title varchar(10),
	lname varchar(20) NOT NULL,
	fname varchar(20) NOT NULL,
	dob timestamp(0),
	flags varchar(2),
	address varchar(35) NOT NULL,
	address2 varchar(35),
	address3 varchar(35),
	address4 varchar(35),
	address5 varchar(35),
	address6 varchar(35),
	zip varchar(10),
	date_selected1 timestamp(0),
	date_selected2 timestamp(0),
	date_selected3 timestamp(0),
	rec_num integer,
	perm_disqual varchar(1),
	source_id varchar(1)
) ;


-- CREATE TABLE schema_version (
-- 	installed_rank numeric(38) NOT NULL,
-- 	version varchar(50),
-- 	description varchar(200) NOT NULL,
-- 	type varchar(20) NOT NULL,
-- 	script varchar(1000) NOT NULL,
-- 	checksum numeric(38),
-- 	installed_by varchar(100) NOT NULL,
-- 	installed_on timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
-- 	execution_time numeric(38) NOT NULL,
-- 	success smallint NOT NULL
-- ) ;
